expected_output = {'network-instance': {'default': {'isis': {'default': {'database': {'rtr1.00-00': {'lsp-id': 'rtr1.00-00',
                                                                                   'sequence': 14,
                                                                                   'checksum': 1363,
                                                                                   'remaining-lifetime': 1029,
                                                                                   'maximum-area-addresses': 3,
                                                                                   'pdu-length': 515,
                                                                                   'system-id': '1111.1111.1111.00',
                                                                                   'overload-bit': False,
                                                                                   'attached-bit': False,
                                                                                   'is-type': 'arcos-isis-types:LEVEL_2',
                                                                                   'received-remaining-lifetime': 1200,
                                                                                   'last-update-time': '2025-12-02T22:10:41.54383+00:00',
                                                                                   'srm-count': 0,
                                                                                   'ssn-count': 0,
                                                                                   'extended-is-neighbor': {'rtr2.00:802': {'system-id': 'rtr2.00',
                                                                                                                            'metric': 10,
                                                                                                                            'instance-id': '802',
                                                                                                                            'two-way': True,
                                                                                                                            'link-id': {'local': 802,
                                                                                                                                        'remote': 801},
                                                                                                                            'ipv4-interface-address': ['10.20.0.10'],
                                                                                                                            'ipv4-neighbor-address': ['10.20.0.20'],
                                                                                                                            'ipv6-interface-address': ['10:20::10'],
                                                                                                                            'asla': {'application': 'flexible-algorithm',
                                                                                                                                     'admin-groups': ['red',
                                                                                                                                                      'green',
                                                                                                                                                      'blue'],
                                                                                                                                     'te-metric': 10,
                                                                                                                                     'min-delay': 5,
                                                                                                                                     'max-delay': 5},
                                                                                                                            'adjacency-sids': [{'sid': 20012,
                                                                                                                                                'flags': ['VALUE',
                                                                                                                                                          'LOCAL'],
                                                                                                                                                'weight': 0}]},
                                                                                                            'rtr2.00:806': {'system-id': 'rtr2.00',
                                                                                                                            'metric': 10,
                                                                                                                            'instance-id': '806',
                                                                                                                            'two-way': True,
                                                                                                                            'link-id': {'local': 806,
                                                                                                                                        'remote': 805},
                                                                                                                            'ipv4-interface-address': ['10.20.2.10'],
                                                                                                                            'ipv4-neighbor-address': ['10.20.2.20'],
                                                                                                                            'ipv6-interface-address': ['10:20:2::10'],
                                                                                                                            'asla': {'application': 'flexible-algorithm',
                                                                                                                                     'admin-groups': ['red',
                                                                                                                                                      'green',
                                                                                                                                                      'blue'],
                                                                                                                                     'te-metric': 10,
                                                                                                                                     'min-delay': 5,
                                                                                                                                     'max-delay': 5},
                                                                                                                            'adjacency-sids': [{'sid': 20122,
                                                                                                                                                'flags': ['VALUE',
                                                                                                                                                          'LOCAL'],
                                                                                                                                                'weight': 0}]},
                                                                                                            'rtr3.00:808': {'system-id': 'rtr3.00',
                                                                                                                            'metric': 10,
                                                                                                                            'instance-id': '808',
                                                                                                                            'two-way': True,
                                                                                                                            'link-id': {'local': 808,
                                                                                                                                        'remote': 807},
                                                                                                                            'ipv4-interface-address': ['10.30.0.10'],
                                                                                                                            'ipv4-neighbor-address': ['10.30.0.30'],
                                                                                                                            'ipv6-interface-address': ['10:30::10'],
                                                                                                                            'asla': {'application': 'flexible-algorithm',
                                                                                                                                     'admin-groups': ['red',
                                                                                                                                                      'green',
                                                                                                                                                      'blue'],
                                                                                                                                     'te-metric': 10,
                                                                                                                                     'min-delay': 5,
                                                                                                                                     'max-delay': 5},
                                                                                                                            'adjacency-sids': [{'sid': 20013,
                                                                                                                                                'flags': ['VALUE',
                                                                                                                                                          'LOCAL'],
                                                                                                                                                'weight': 0}]}},
                                                                                   'extended-ipv4-reachability': {'10.20.0.0/24': {'ip-prefix': '10.20.0.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '10.20.2.0/24': {'ip-prefix': '10.20.2.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '10.30.0.0/24': {'ip-prefix': '10.30.0.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '1.1.1.1/32': {'ip-prefix': '1.1.1.1',
                                                                                                                                 'prefix-len': 32,
                                                                                                                                 'metric': 10,
                                                                                                                                 'up-down': False,
                                                                                                                                 'prefix-sids': [{'algorithm': 'SPF',
                                                                                                                                                  'sid': 111,
                                                                                                                                                  'flags': ['NODE',
                                                                                                                                                            'NO_PHP',
                                                                                                                                                            'EXPLICIT_NULL']}],
                                                                                                                                 'flags': ['arcos-isis-types:ISIS_PREFIX_NODE_FLAG']}},
                                                                                   'ipv6-reachability': {'10:20::/120': {'ip-prefix': '10:20::',
                                                                                                                         'prefix-len': 120,
                                                                                                                         'metric': 10,
                                                                                                                         'up-down': False},
                                                                                                         '10:20:2::/120': {'ip-prefix': '10:20:2::',
                                                                                                                           'prefix-len': 120,
                                                                                                                           'metric': 10,
                                                                                                                           'up-down': False},
                                                                                                         '10:30::/120': {'ip-prefix': '10:30::',
                                                                                                                         'prefix-len': 120,
                                                                                                                         'metric': 10,
                                                                                                                         'up-down': False}},
                                                                                   'tlvs': {'area-addresses': ['49.0001'],
                                                                                            'nlpid': ['IPV6',
                                                                                                      'IPV4'],
                                                                                            'hostname': 'rtr1',
                                                                                            'router-capabilities': {'instance-number': 1,
                                                                                                                    'router-id': '1.1.1.1',
                                                                                                                    'sr-algorithms': ['SPF'],
                                                                                                                    'sr-capability': {'flags': ['IPV4_MPLS',
                                                                                                                                                'IPV6_MPLS'],
                                                                                                                                      'range': 10000,
                                                                                                                                      'label': 10000},
                                                                                                                    'srlb': {'range': 10000,
                                                                                                                             'label': 20000}}}},
                                                                    'rtr2.00-00': {'lsp-id': 'rtr2.00-00',
                                                                                   'sequence': 12,
                                                                                   'checksum': 34823,
                                                                                   'remaining-lifetime': 1080,
                                                                                   'maximum-area-addresses': 3,
                                                                                   'pdu-length': 481,
                                                                                   'system-id': '2222.2222.2222.00',
                                                                                   'overload-bit': False,
                                                                                   'attached-bit': False,
                                                                                   'is-type': 'arcos-isis-types:LEVEL_2',
                                                                                   'received-remaining-lifetime': 1198,
                                                                                   'last-update-ifindex': 806,
                                                                                   'last-update-time': '2025-12-02T22:11:33.80158+00:00',
                                                                                   'srm-count': 0,
                                                                                   'ssn-count': 0,
                                                                                   'extended-is-neighbor': {'rtr1.00:1': {'system-id': 'rtr1.00',
                                                                                                                          'metric': 10,
                                                                                                                          'instance-id': '1',
                                                                                                                          'two-way': True,
                                                                                                                          'link-id': {'local': 801,
                                                                                                                                      'remote': 802},
                                                                                                                          'ipv4-interface-address': ['10.20.0.20'],
                                                                                                                          'ipv4-neighbor-address': ['10.20.0.10'],
                                                                                                                          'ipv6-interface-address': ['10:20::20'],
                                                                                                                          'asla': {'application': 'flexible-algorithm',
                                                                                                                                   'admin-groups': ['red',
                                                                                                                                                    'green',
                                                                                                                                                    'blue'],
                                                                                                                                   'te-metric': 10,
                                                                                                                                   'min-delay': 5,
                                                                                                                                   'max-delay': 5},
                                                                                                                          'adjacency-sids': [{'sid': 20021,
                                                                                                                                              'flags': ['VALUE',
                                                                                                                                                        'LOCAL'],
                                                                                                                                              'weight': 0}]},
                                                                                                            'rtr1.00:2': {'system-id': 'rtr1.00',
                                                                                                                          'metric': 10,
                                                                                                                          'instance-id': '2',
                                                                                                                          'two-way': True,
                                                                                                                          'link-id': {'local': 805,
                                                                                                                                      'remote': 806},
                                                                                                                          'ipv4-interface-address': ['10.20.2.20'],
                                                                                                                          'ipv4-neighbor-address': ['10.20.2.10'],
                                                                                                                          'ipv6-interface-address': ['10:20:2::20'],
                                                                                                                          'asla': {'application': 'flexible-algorithm',
                                                                                                                                   'admin-groups': ['red',
                                                                                                                                                    'green',
                                                                                                                                                    'blue'],
                                                                                                                                   'te-metric': 10,
                                                                                                                                   'min-delay': 5,
                                                                                                                                   'max-delay': 5},
                                                                                                                          'adjacency-sids': [{'sid': 20122,
                                                                                                                                              'flags': ['VALUE',
                                                                                                                                                        'LOCAL'],
                                                                                                                                              'weight': 0}]},
                                                                                                            'rtr3.00:3': {'system-id': 'rtr3.00',
                                                                                                                          'metric': 10,
                                                                                                                          'instance-id': '3',
                                                                                                                          'two-way': True,
                                                                                                                          'link-id': {'local': 804,
                                                                                                                                      'remote': 803},
                                                                                                                          'ipv4-interface-address': ['20.30.0.20'],
                                                                                                                          'ipv4-neighbor-address': ['20.30.0.30'],
                                                                                                                          'ipv6-interface-address': ['20:30::20'],
                                                                                                                          'adjacency-sids': [{'sid': 20023,
                                                                                                                                              'flags': ['VALUE',
                                                                                                                                                        'LOCAL'],
                                                                                                                                              'weight': 0}]}},
                                                                                   'extended-ipv4-reachability': {'10.20.0.0/24': {'ip-prefix': '10.20.0.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '10.20.2.0/24': {'ip-prefix': '10.20.2.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '20.30.0.0/24': {'ip-prefix': '20.30.0.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '2.2.2.2/32': {'ip-prefix': '2.2.2.2',
                                                                                                                                 'prefix-len': 32,
                                                                                                                                 'metric': 10,
                                                                                                                                 'up-down': False,
                                                                                                                                 'prefix-sids': [{'algorithm': 'SPF',
                                                                                                                                                  'sid': 222,
                                                                                                                                                  'flags': ['NODE',
                                                                                                                                                            'NO_PHP',
                                                                                                                                                            'EXPLICIT_NULL']}],
                                                                                                                                 'flags': ['arcos-isis-types:ISIS_PREFIX_NODE_FLAG']}},
                                                                                   'ipv6-reachability': {'10:20::/120': {'ip-prefix': '10:20::',
                                                                                                                         'prefix-len': 120,
                                                                                                                         'metric': 10,
                                                                                                                         'up-down': False},
                                                                                                         '10:20:2::/120': {'ip-prefix': '10:20:2::',
                                                                                                                           'prefix-len': 120,
                                                                                                                           'metric': 10,
                                                                                                                           'up-down': False},
                                                                                                         '20:30::/120': {'ip-prefix': '20:30::',
                                                                                                                         'prefix-len': 120,
                                                                                                                         'metric': 10,
                                                                                                                         'up-down': False}},
                                                                                   'tlvs': {'area-addresses': ['49.1234'],
                                                                                            'nlpid': ['IPV6',
                                                                                                      'IPV4'],
                                                                                            'hostname': 'rtr2',
                                                                                            'router-capabilities': {'instance-number': 1,
                                                                                                                    'router-id': '2.2.2.2',
                                                                                                                    'sr-algorithms': ['SPF'],
                                                                                                                    'sr-capability': {'flags': ['IPV4_MPLS',
                                                                                                                                                'IPV6_MPLS'],
                                                                                                                                      'range': 10000,
                                                                                                                                      'label': 10000},
                                                                                                                    'srlb': {'range': 10000,
                                                                                                                             'label': 20000}}}},
                                                                    'rtr3.00-00': {'lsp-id': 'rtr3.00-00',
                                                                                   'sequence': 12,
                                                                                   'checksum': 56363,
                                                                                   'remaining-lifetime': 807,
                                                                                   'maximum-area-addresses': 3,
                                                                                   'pdu-length': 354,
                                                                                   'system-id': '3333.3333.3333.00',
                                                                                   'overload-bit': False,
                                                                                   'attached-bit': False,
                                                                                   'is-type': 'arcos-isis-types:LEVEL_2',
                                                                                   'received-remaining-lifetime': 1199,
                                                                                   'last-update-ifindex': 808,
                                                                                   'last-update-time': '2025-12-02T22:07:00.20759+00:00',
                                                                                   'srm-count': 0,
                                                                                   'ssn-count': 0,
                                                                                   'extended-is-neighbor': {'rtr1.00:1': {'system-id': 'rtr1.00',
                                                                                                                          'metric': 10,
                                                                                                                          'instance-id': '1',
                                                                                                                          'two-way': True,
                                                                                                                          'link-id': {'local': 807,
                                                                                                                                      'remote': 808},
                                                                                                                          'ipv4-interface-address': ['10.30.0.30'],
                                                                                                                          'ipv4-neighbor-address': ['10.30.0.10'],
                                                                                                                          'ipv6-interface-address': ['10:30::30'],
                                                                                                                          'asla': {'application': 'flexible-algorithm',
                                                                                                                                   'admin-groups': ['red',
                                                                                                                                                    'green',
                                                                                                                                                    'blue'],
                                                                                                                                   'te-metric': 10,
                                                                                                                                   'min-delay': 5,
                                                                                                                                   'max-delay': 5},
                                                                                                                          'adjacency-sids': [{'sid': 20031,
                                                                                                                                              'flags': ['VALUE',
                                                                                                                                                        'LOCAL'],
                                                                                                                                              'weight': 0}]},
                                                                                                            'rtr2.00:2': {'system-id': 'rtr2.00',
                                                                                                                          'metric': 10,
                                                                                                                          'instance-id': '2',
                                                                                                                          'two-way': True,
                                                                                                                          'link-id': {'local': 803,
                                                                                                                                      'remote': 804},
                                                                                                                          'ipv4-interface-address': ['20.30.0.30'],
                                                                                                                          'ipv4-neighbor-address': ['20.30.0.20'],
                                                                                                                          'ipv6-interface-address': ['20:30::30'],
                                                                                                                          'adjacency-sids': [{'sid': 20032,
                                                                                                                                              'flags': ['VALUE',
                                                                                                                                                        'LOCAL'],
                                                                                                                                              'weight': 0}]}},
                                                                                   'extended-ipv4-reachability': {'10.30.0.0/24': {'ip-prefix': '10.30.0.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '20.30.0.0/24': {'ip-prefix': '20.30.0.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '3.3.3.3/32': {'ip-prefix': '3.3.3.3',
                                                                                                                                 'prefix-len': 32,
                                                                                                                                 'metric': 10,
                                                                                                                                 'up-down': False,
                                                                                                                                 'prefix-sids': [{'algorithm': 'SPF',
                                                                                                                                                  'sid': 333,
                                                                                                                                                  'flags': ['NODE',
                                                                                                                                                            'NO_PHP',
                                                                                                                                                            'EXPLICIT_NULL']}],
                                                                                                                                 'flags': ['arcos-isis-types:ISIS_PREFIX_NODE_FLAG']}},
                                                                                   'ipv6-reachability': {'10:30::/120': {'ip-prefix': '10:30::',
                                                                                                                         'prefix-len': 120,
                                                                                                                         'metric': 10,
                                                                                                                         'up-down': False},
                                                                                                         '20:30::/120': {'ip-prefix': '20:30::',
                                                                                                                         'prefix-len': 120,
                                                                                                                         'metric': 10,
                                                                                                                         'up-down': False}},
                                                                                   'tlvs': {'area-addresses': ['49.1234'],
                                                                                            'nlpid': ['IPV6',
                                                                                                      'IPV4'],
                                                                                            'hostname': 'rtr3',
                                                                                            'router-capabilities': {'instance-number': 1,
                                                                                                                    'router-id': '3.3.3.3',
                                                                                                                    'sr-algorithms': ['SPF'],
                                                                                                                    'sr-capability': {'flags': ['IPV4_MPLS',
                                                                                                                                                'IPV6_MPLS'],
                                                                                                                                      'range': 10000,
                                                                                                                                      'label': 10000},
                                                                                                                    'srlb': {'range': 10000,
                                                                                                                             'label': 20000}}}}}}}}}}
