expected_output = {'network-instance': {'default': {'isis': {'default': {'database': {'rtr1.00-00': {'lsp-id': 'rtr1.00-00',
                                                                                   'sequence': 151,
                                                                                   'checksum': 12778,
                                                                                   'remaining-lifetime': 1078,
                                                                                   'maximum-area-addresses': 3,
                                                                                   'pdu-length': 147,
                                                                                   'system-id': '1111.1111.1111.00',
                                                                                   'overload-bit': False,
                                                                                   'attached-bit': False,
                                                                                   'is-type': 'arcos-isis-types:LEVEL_2',
                                                                                   'received-remaining-lifetime': 1193,
                                                                                   'last-update-ifindex': 803,
                                                                                   'last-update-time': '2025-11-27T01:16:51.93868+00:00',
                                                                                   'srm-count': 0,
                                                                                   'ssn-count': 0,
                                                                                   'extended-is-neighbor': {'rtr2.00:1': {'system-id': 'rtr2.00',
                                                                                                                          'metric': 10,
                                                                                                                          'instance-id': '1',
                                                                                                                          'two-way': True,
                                                                                                                          'link-id': {'local': 802,
                                                                                                                                      'remote': 801},
                                                                                                                          'ipv4-interface-address': ['10.20.0.10'],
                                                                                                                          'ipv4-neighbor-address': ['10.20.0.20']}},
                                                                                   'extended-ipv4-reachability': {'10.20.0.0/24': {'ip-prefix': '10.20.0.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '1.1.1.1/32': {'ip-prefix': '1.1.1.1',
                                                                                                                                 'prefix-len': 32,
                                                                                                                                 'metric': 10,
                                                                                                                                 'up-down': False,
                                                                                                                                 'flags': ['arcos-isis-types:ISIS_PREFIX_NODE_FLAG']}},
                                                                                   'mt-ipv6-reachability': {'2400:2020:0:1191::91/128': {'ip-prefix': '2400:2020:0:1191::91',
                                                                                                                                         'prefix-len': 128,
                                                                                                                                         'metric': 10,
                                                                                                                                         'mt-id': 2,
                                                                                                                                         'up-down': False,
                                                                                                                                         'flags': ['arcos-isis-types:ISIS_PREFIX_NODE_FLAG']}},
                                                                                   'tlvs': {'area-addresses': ['49.0001'],
                                                                                            'nlpid': ['IPV6',
                                                                                                      'IPV4'],
                                                                                            'hostname': 'rtr1'}},
                                                                    'rtr2.00-00': {'lsp-id': 'rtr2.00-00',
                                                                                   'sequence': 153,
                                                                                   'checksum': 20742,
                                                                                   'remaining-lifetime': 1078,
                                                                                   'maximum-area-addresses': 3,
                                                                                   'pdu-length': 185,
                                                                                   'system-id': '2222.2222.2222.00',
                                                                                   'overload-bit': False,
                                                                                   'attached-bit': False,
                                                                                   'is-type': 'arcos-isis-types:LEVEL_2',
                                                                                   'received-remaining-lifetime': 1195,
                                                                                   'last-update-ifindex': 803,
                                                                                   'last-update-time': '2025-11-27T01:16:49.90052+00:00',
                                                                                   'srm-count': 0,
                                                                                   'ssn-count': 0,
                                                                                   'extended-is-neighbor': {'rtr1.00:2': {'system-id': 'rtr1.00',
                                                                                                                          'metric': 10,
                                                                                                                          'instance-id': '2',
                                                                                                                          'two-way': True,
                                                                                                                          'link-id': {'local': 801,
                                                                                                                                      'remote': 802},
                                                                                                                          'ipv4-interface-address': ['10.20.0.20'],
                                                                                                                          'ipv4-neighbor-address': ['10.20.0.10']},
                                                                                                            'rtr3.00:1': {'system-id': 'rtr3.00',
                                                                                                                          'metric': 10,
                                                                                                                          'instance-id': '1',
                                                                                                                          'two-way': True,
                                                                                                                          'link-id': {'local': 804,
                                                                                                                                      'remote': 803},
                                                                                                                          'ipv4-interface-address': ['20.30.0.20'],
                                                                                                                          'ipv4-neighbor-address': ['20.30.0.30']}},
                                                                                   'extended-ipv4-reachability': {'10.20.0.0/24': {'ip-prefix': '10.20.0.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '20.30.0.0/24': {'ip-prefix': '20.30.0.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '2.2.2.2/32': {'ip-prefix': '2.2.2.2',
                                                                                                                                 'prefix-len': 32,
                                                                                                                                 'metric': 10,
                                                                                                                                 'up-down': False,
                                                                                                                                 'flags': ['arcos-isis-types:ISIS_PREFIX_NODE_FLAG']}},
                                                                                   'mt-ipv6-reachability': {'2400:2020:0:2291::91/128': {'ip-prefix': '2400:2020:0:2291::91',
                                                                                                                                         'prefix-len': 128,
                                                                                                                                         'metric': 10,
                                                                                                                                         'mt-id': 2,
                                                                                                                                         'up-down': False,
                                                                                                                                         'flags': ['arcos-isis-types:ISIS_PREFIX_NODE_FLAG']}},
                                                                                   'tlvs': {'area-addresses': ['49.0002'],
                                                                                            'nlpid': ['IPV4'],
                                                                                            'hostname': 'rtr2'}},
                                                                    'rtr3.00-00': {'lsp-id': 'rtr3.00-00',
                                                                                   'sequence': 128,
                                                                                   'checksum': 1745,
                                                                                   'remaining-lifetime': 1072,
                                                                                   'maximum-area-addresses': 3,
                                                                                   'pdu-length': 172,
                                                                                   'system-id': '3333.3333.3333.00',
                                                                                   'overload-bit': False,
                                                                                   'attached-bit': False,
                                                                                   'is-type': 'arcos-isis-types:LEVEL_2',
                                                                                   'received-remaining-lifetime': 1200,
                                                                                   'last-update-time': '2025-11-27T01:16:39.25331+00:00',
                                                                                   'srm-count': 0,
                                                                                   'ssn-count': 0,
                                                                                   'extended-is-neighbor': {'rtr2.00:803': {'system-id': 'rtr2.00',
                                                                                                                            'metric': 10,
                                                                                                                            'instance-id': '803',
                                                                                                                            'two-way': True,
                                                                                                                            'link-id': {'local': 803,
                                                                                                                                        'remote': 804},
                                                                                                                            'ipv4-interface-address': ['20.30.0.30'],
                                                                                                                            'ipv4-neighbor-address': ['20.30.0.20']}},
                                                                                   'extended-ipv4-reachability': {'20.30.0.0/24': {'ip-prefix': '20.30.0.0',
                                                                                                                                   'prefix-len': 24,
                                                                                                                                   'metric': 10,
                                                                                                                                   'up-down': False},
                                                                                                                  '3.3.3.3/32': {'ip-prefix': '3.3.3.3',
                                                                                                                                 'prefix-len': 32,
                                                                                                                                 'metric': 10,
                                                                                                                                 'up-down': False,
                                                                                                                                 'flags': ['arcos-isis-types:ISIS_PREFIX_NODE_FLAG']}},
                                                                                   'mt-ipv6-reachability': {'10:30::/120': {'ip-prefix': '10:30::',
                                                                                                                            'prefix-len': 120,
                                                                                                                            'metric': 10,
                                                                                                                            'mt-id': 2,
                                                                                                                            'up-down': False},
                                                                                                            '2400:2020:0:3391::91/128': {'ip-prefix': '2400:2020:0:3391::91',
                                                                                                                                         'prefix-len': 128,
                                                                                                                                         'metric': 10,
                                                                                                                                         'mt-id': 2,
                                                                                                                                         'up-down': False,
                                                                                                                                         'flags': ['arcos-isis-types:ISIS_PREFIX_NODE_FLAG']}},
                                                                                   'tlvs': {'area-addresses': ['49.1234'],
                                                                                            'nlpid': ['IPV6',
                                                                                                      'IPV4'],
                                                                                            'hostname': 'rtr3'}}}}}}}}
