expected_output = {'network-instance': {'default': {'isis': {'default': {'global': {'micro-loop-avoidance': {'srv6-enabled': False,
                                                                                           'rib-update-delay': 8000,
                                                                                           'status': {'0-2-ISIS_MT_ID0_STANDARD': {'algo': 0,
                                                                                                                                   'level': 2,
                                                                                                                                   'topology-id': 'ISIS_MT_ID0_STANDARD',
                                                                                                                                   'mla-state': 'ACTIVE',
                                                                                                                                   'last-event': 'LINK-DOWN',
                                                                                                                                   'near-node': 'rtr1',
                                                                                                                                   'far-node': 'rtr2',
                                                                                                                                   'spf-start-timestamp': '2026-07-10T04:12:07.100000+00:00'},
                                                                                                      '128-2-ISIS_MT_ID0_STANDARD': {'algo': 128,
                                                                                                                                     'level': 2,
                                                                                                                                     'topology-id': 'ISIS_MT_ID0_STANDARD',
                                                                                                                                     'mla-state': 'EXPIRED',
                                                                                                                                     'last-event': 'OVERLOAD-SET',
                                                                                                                                     'near-node': 'rtr1',
                                                                                                                                     'far-node': 'rtr2',
                                                                                                                                     'spf-start-timestamp': '2026-07-10T04:12:09.200000+00:00'}}}}}}}}}
