expected_output = {'network-instance': {'default': {'address-family': 'IPV4',
                                  'nexthop-entries': {'2147483650': {'flags': 'LOCAL MIXED_REACH',
                                                                     'index': 2147483650,
                                                                     'level': 1,
                                                                     'paths': {'0': {'network-instance': 'default',
                                                                                     'path-id': 2147483649,
                                                                                     'path-type': 'DROP'}}},
                                                      '230': {'flags': 'IP_REACH',
                                                              'index': 230,
                                                              'level': 1,
                                                              'paths': {'0': {'network-instance': 'default',
                                                                              'next-hop': '1.1.1.1',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 229,
                                                                              'path-type': 'LOCAL_V4'}}},
                                                      '24': {'flags': 'IP_REACH',
                                                             'index': 24,
                                                             'level': 1,
                                                             'paths': {'0': {'interface': 'swp2',
                                                                             'network-instance': 'default',
                                                                             'next-hop': '10.14.2.4',
                                                                             'nh-type': 'IPV4',
                                                                             'path-id': 23,
                                                                             'path-type': 'CONNECTED_V4'}}},
                                                      '437': {'flags': 'IP_REACH',
                                                              'index': 437,
                                                              'level': 1,
                                                              'paths': {'0': {'network-instance': 'default',
                                                                              'next-hop': '10.12.1.1',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 436,
                                                                              'path-type': 'GLEAN_V4'}}},
                                                      '439': {'flags': 'IP_REACH',
                                                              'index': 439,
                                                              'level': 1,
                                                              'paths': {'0': {'network-instance': 'default',
                                                                              'next-hop': '10.12.1.1',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 438,
                                                                              'path-type': 'LOCAL_V4'}}},
                                                      '441': {'flags': 'IP_REACH',
                                                              'index': 441,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp1',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.12.1.2',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 440,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '536871547': {'flags': 'LOCAL MPLS_REACH',
                                                                    'index': 536871547,
                                                                    'level': 1,
                                                                    'paths': {'0': {'interface': 'swp1',
                                                                                    'network-instance': 'default',
                                                                                    'next-hop': '10.12.1.2',
                                                                                    'nh-type': 'IPV4',
                                                                                    'path-id': 536871546,
                                                                                    'path-type': 'CONNECTED_V4',
                                                                                    'push-label': [3]}},
                                                                    'source-nexthop-index': 635},
                                                      '536871549': {'flags': 'LOCAL MPLS_REACH',
                                                                    'index': 536871549,
                                                                    'level': 1,
                                                                    'paths': {'0': {'interface': 'swp2',
                                                                                    'network-instance': 'default',
                                                                                    'next-hop': '10.14.2.4',
                                                                                    'nh-type': 'IPV4',
                                                                                    'path-id': 536871548,
                                                                                    'path-type': 'CONNECTED_V4',
                                                                                    'push-label': [3]}},
                                                                    'source-nexthop-index': 637},
                                                      '536871551': {'flags': 'LOCAL MPLS_REACH',
                                                                    'index': 536871551,
                                                                    'level': 1,
                                                                    'paths': {'0': {'interface': 'swp3',
                                                                                    'network-instance': 'default',
                                                                                    'next-hop': '10.14.3.4',
                                                                                    'nh-type': 'IPV4',
                                                                                    'path-id': 536871550,
                                                                                    'path-type': 'CONNECTED_V4',
                                                                                    'push-label': [3]}},
                                                                    'source-nexthop-index': 639},
                                                      '536871553': {'flags': 'RECURSIVE LOCAL '
                                                                             'MPLS_REACH',
                                                                    'index': 536871553,
                                                                    'level': 2,
                                                                    'paths': {'0': {'igp-path-id': [1073742454],
                                                                                    'igp-path-type': 2,
                                                                                    'network-instance': 'default',
                                                                                    'next-hop': 630,
                                                                                    'nh-type': 'IGP',
                                                                                    'num-coll-paths': 1,
                                                                                    'path-id': 536871552,
                                                                                    'path-type': 'RECURSIVE',
                                                                                    'push-label': [3]}},
                                                                    'source-nexthop-index': 641},
                                                      '536871555': {'flags': 'LOCAL MPLS_REACH',
                                                                    'index': 536871555,
                                                                    'level': 1,
                                                                    'paths': {'0': {'interface': 'swp4',
                                                                                    'network-instance': 'default',
                                                                                    'next-hop': '10.15.4.5',
                                                                                    'nh-type': 'IPV4',
                                                                                    'path-id': 536871554,
                                                                                    'path-type': 'CONNECTED_V4',
                                                                                    'push-label': [3]}},
                                                                    'source-nexthop-index': 643},
                                                      '6': {'flags': 'IP_REACH',
                                                            'index': 6,
                                                            'level': 1,
                                                            'paths': {'0': {'network-instance': 'default',
                                                                            'next-hop': '10.14.2.1',
                                                                            'nh-type': 'IPV4',
                                                                            'path-id': 5,
                                                                            'path-type': 'GLEAN_V4'}}},
                                                      '615': {'flags': 'IP_REACH',
                                                              'index': 615,
                                                              'level': 1,
                                                              'paths': {'0': {'network-instance': 'default',
                                                                              'next-hop': '10.14.3.1',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 614,
                                                                              'path-type': 'GLEAN_V4'}}},
                                                      '617': {'flags': 'IP_REACH',
                                                              'index': 617,
                                                              'level': 1,
                                                              'paths': {'0': {'network-instance': 'default',
                                                                              'next-hop': '10.14.3.1',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 616,
                                                                              'path-type': 'LOCAL_V4'}}},
                                                      '619': {'flags': 'IP_REACH',
                                                              'index': 619,
                                                              'level': 1,
                                                              'paths': {'0': {'network-instance': 'default',
                                                                              'next-hop': '10.15.4.1',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 618,
                                                                              'path-type': 'GLEAN_V4'}}},
                                                      '621': {'flags': 'IP_REACH',
                                                              'index': 621,
                                                              'level': 1,
                                                              'paths': {'0': {'network-instance': 'default',
                                                                              'next-hop': '10.15.4.1',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 620,
                                                                              'path-type': 'LOCAL_V4'}}},
                                                      '623': {'flags': 'IP_REACH',
                                                              'index': 623,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp3',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.14.3.4',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 622,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '625': {'flags': 'IP_REACH',
                                                              'index': 625,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp4',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.15.4.5',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 624,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '630': {'flags': 'IP_REACH',
                                                              'index': 630,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp3',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.14.3.4',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 622,
                                                                              'path-type': 'CONNECTED_V4'},
                                                                        '1': {'interface': 'swp2',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.14.2.4',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 23,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '631': {'flags': 'IP_REACH',
                                                              'index': 631,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp4',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.15.4.5',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 624,
                                                                              'path-type': 'CONNECTED_V4'},
                                                                        '1': {'interface': 'swp1',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.12.1.2',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 440,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '632': {'flags': 'IP_REACH',
                                                              'index': 632,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp4',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.15.4.5',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 624,
                                                                              'path-type': 'CONNECTED_V4'},
                                                                        '1': {'interface': 'swp3',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.14.3.4',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 622,
                                                                              'path-type': 'CONNECTED_V4'},
                                                                        '2': {'interface': 'swp2',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.14.2.4',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 23,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '633': {'flags': 'IP_REACH',
                                                              'index': 633,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp3',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.14.3.4',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 622,
                                                                              'path-type': 'CONNECTED_V4'},
                                                                        '1': {'interface': 'swp1',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.12.1.2',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 440,
                                                                              'path-type': 'CONNECTED_V4'},
                                                                        '2': {'interface': 'swp2',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.14.2.4',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 23,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '635': {'eos0-nexthop-index': 536871547,
                                                              'flags': 'IP_REACH',
                                                              'index': 635,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp1',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.12.1.2',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 634,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '637': {'eos0-nexthop-index': 536871549,
                                                              'flags': 'IP_REACH',
                                                              'index': 637,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp2',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.14.2.4',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 636,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '639': {'eos0-nexthop-index': 536871551,
                                                              'flags': 'IP_REACH',
                                                              'index': 639,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp3',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.14.3.4',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 638,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '641': {'eos0-nexthop-index': 536871553,
                                                              'flags': 'RECURSIVE IP_REACH',
                                                              'index': 641,
                                                              'level': 2,
                                                              'paths': {'0': {'igp-path-id': [622,
                                                                                              23],
                                                                              'network-instance': 'default',
                                                                              'next-hop': 630,
                                                                              'nh-type': 'IGP',
                                                                              'num-coll-paths': 2,
                                                                              'path-id': 640,
                                                                              'path-type': 'RECURSIVE'}}},
                                                      '643': {'eos0-nexthop-index': 536871555,
                                                              'flags': 'IP_REACH',
                                                              'index': 643,
                                                              'level': 1,
                                                              'paths': {'0': {'interface': 'swp4',
                                                                              'network-instance': 'default',
                                                                              'next-hop': '10.15.4.5',
                                                                              'nh-type': 'IPV4',
                                                                              'path-id': 642,
                                                                              'path-type': 'CONNECTED_V4'}}},
                                                      '8': {'flags': 'IP_REACH',
                                                            'index': 8,
                                                            'level': 1,
                                                            'paths': {'0': {'network-instance': 'default',
                                                                            'next-hop': '10.14.2.1',
                                                                            'nh-type': 'IPV4',
                                                                            'path-id': 7,
                                                                            'path-type': 'LOCAL_V4'}}}}}}}
