expected_output = {'sessions': {'1.1.1.1': {'forwarding-holdtime': 0,
                          'graceful-restart': 'Disabled',
                          'graceful-restart-state': 'Inactive',
                          'keepalive-interval': 10,
                          'keepalive-timeout': 30,
                          'last-established-time': '2026-03-31T17:38:22.136631+00:00',
                          'last-update-timestamp': '2026-03-31T17:38:22.136631+00:00',
                          'local-address': '2.2.2.2',
                          'local-label-space-id': 0,
                          'local-lsr-id': '2.2.2.2',
                          'peer-address': '1.1.1.1',
                          'reconnect-time': 0,
                          'recovery-time': 0,
                          'remote-label-space-id': 0,
                          'remote-lsr-id': '1.1.1.1',
                          'reset-count': 1,
                          'session-role': 'Active',
                          'session-state': 'Operational',
                          'uptime': '0d 00:00:11'},
              '3.3.3.3': {'forwarding-holdtime': 0,
                          'graceful-restart': 'Disabled',
                          'graceful-restart-state': 'Inactive',
                          'keepalive-interval': 10,
                          'keepalive-timeout': 30,
                          'last-established-time': '2026-03-31T17:38:10.205811+00:00',
                          'last-update-timestamp': '2026-03-31T17:38:10.20581+00:00',
                          'local-address': '2.2.2.2',
                          'local-label-space-id': 0,
                          'local-lsr-id': '2.2.2.2',
                          'peer-address': '3.3.3.3',
                          'reconnect-time': 0,
                          'recovery-time': 0,
                          'remote-label-space-id': 0,
                          'remote-lsr-id': '3.3.3.3',
                          'reset-count': 0,
                          'session-role': 'Passive',
                          'session-state': 'Operational',
                          'uptime': '0d 00:00:23'}}}
