expected_output = {'network-instance': {'default': {'address-family': 'IPV6',
                                  'entries': {'2001::5/128': {'best-protocol': 'ISIS',
                                                              'hw-update': {'install-ack': False,
                                                                            'status-code': 0,
                                                                            'version': '0'},
                                                              'origins': {'0': {'flags': 'ECMP_FEC_OPTIMIZE',
                                                                                'label-pref': 114,
                                                                                'last-updated': '2026-03-08T14:23:27.960489-00:00',
                                                                                'metric': 20,
                                                                                'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                    'interface': 'swp4',
                                                                                                    'network-instance': 'default',
                                                                                                    'next-hop': 'fe80::b8d0:10ff:feb5:8ced',
                                                                                                    'pathid': '268435889',
                                                                                                    'pushed-mpls-label-stack': [3],
                                                                                                    'type': 'IPV6',
                                                                                                    'weight': 100}},
                                                                                'nhid': '268435890',
                                                                                'opaque-data': '0',
                                                                                'origin-protocol': 'ISIS',
                                                                                'pref': 115,
                                                                                'protocol-name': 'isis-default@default',
                                                                                'route-type': 'ISIS_L2',
                                                                                'tag': 0}},
                                                              'prefix': '2001::5/128'}}}}}
