expected_output = {'network-instance': {'default': {'address-family': 'IPV4',
                                  'entries': {'5.5.5.5/32': {'best-protocol': 'ISIS',
                                                             'hw-update': {'install-ack': False,
                                                                           'status-code': 0,
                                                                           'version': '0'},
                                                             'origins': {'0': {'flags': '',
                                                                               'label-pref': 114,
                                                                               'last-updated': '2026-03-08T10:25:58.742977-00:00',
                                                                               'metric': 20,
                                                                               'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                   'interface': 'swp4',
                                                                                                   'network-instance': 'default',
                                                                                                   'next-hop': '10.15.4.5',
                                                                                                   'pathid': '642',
                                                                                                   'pushed-mpls-label-stack': [3],
                                                                                                   'type': 'IPV4',
                                                                                                   'weight': 100}},
                                                                               'nhid': '643',
                                                                               'opaque-data': '0',
                                                                               'origin-protocol': 'ISIS',
                                                                               'pref': 115,
                                                                               'protocol-name': 'isis-default@default',
                                                                               'route-type': 'ISIS_L2',
                                                                               'tag': 0}},
                                                             'prefix': '5.5.5.5/32'}}}}}
