expected_output = {'network-instance': {'default': {'address-family': 'IPV4',
                                  'entries': {'1.1.1.1/32': {'best-protocol': 'DIRECTLY_CONNECTED',
                                                             'hw-update': {'install-ack': False,
                                                                           'status-code': 0,
                                                                           'version': '0'},
                                                             'origins': {'0': {'flags': '',
                                                                               'last-updated': '2026-01-27T17:30:52.546417-00:00',
                                                                               'metric': 1,
                                                                               'next-hops': {'0': {'flags': 'GLEAN '
                                                                                                            'LOCAL',
                                                                                                   'interface': 'loopback0',
                                                                                                   'network-instance': 'default',
                                                                                                   'next-hop': '1.1.1.1',
                                                                                                   'pathid': '229',
                                                                                                   'type': 'IPV4',
                                                                                                   'weight': 100}},
                                                                               'nhid': '230',
                                                                               'opaque-data': '0',
                                                                               'origin-protocol': 'DIRECTLY_CONNECTED',
                                                                               'pref': 0,
                                                                               'protocol-name': 'directly_connected',
                                                                               'tag': 0}},
                                                             'prefix': '1.1.1.1/32'},
                                              '10.12.1.0/24': {'best-protocol': 'DIRECTLY_CONNECTED',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-02-02T20:58:08.592847-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'GLEAN',
                                                                                                     'interface': 'swp1',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.12.1.1',
                                                                                                     'pathid': '436',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '437',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'DIRECTLY_CONNECTED',
                                                                                 'pref': 0,
                                                                                 'protocol-name': 'directly_connected',
                                                                                 'tag': 0}},
                                                               'prefix': '10.12.1.0/24'},
                                              '10.12.1.1/32': {'best-protocol': 'DIRECTLY_CONNECTED',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-02-02T20:58:08.592948-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'LOCAL',
                                                                                                     'interface': 'swp1',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.12.1.1',
                                                                                                     'pathid': '438',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '439',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'DIRECTLY_CONNECTED',
                                                                                 'pref': 0,
                                                                                 'protocol-name': 'directly_connected',
                                                                                 'tag': 0}},
                                                               'prefix': '10.12.1.1/32'},
                                              '10.12.1.2/32': {'best-protocol': 'arcos-openconfig-policy-types:ADJACENCY',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-02-02T20:58:08.65838-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp1',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.12.1.2',
                                                                                                     'pathid': '440',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '441',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'arcos-openconfig-policy-types:ADJACENCY',
                                                                                 'pref': 1,
                                                                                 'protocol-name': 'adjacency',
                                                                                 'tag': 1}},
                                                               'prefix': '10.12.1.2/32'},
                                              '10.14.2.0/24': {'best-protocol': 'DIRECTLY_CONNECTED',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-01-21T12:26:40.10032-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'GLEAN',
                                                                                                     'interface': 'swp2',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.14.2.1',
                                                                                                     'pathid': '5',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '6',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'DIRECTLY_CONNECTED',
                                                                                 'pref': 0,
                                                                                 'protocol-name': 'directly_connected',
                                                                                 'tag': 0}},
                                                               'prefix': '10.14.2.0/24'},
                                              '10.14.2.1/32': {'best-protocol': 'DIRECTLY_CONNECTED',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-01-21T12:26:40.100452-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'LOCAL',
                                                                                                     'interface': 'swp2',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.14.2.1',
                                                                                                     'pathid': '7',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '8',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'DIRECTLY_CONNECTED',
                                                                                 'pref': 0,
                                                                                 'protocol-name': 'directly_connected',
                                                                                 'tag': 0}},
                                                               'prefix': '10.14.2.1/32'},
                                              '10.14.2.4/32': {'best-protocol': 'arcos-openconfig-policy-types:ADJACENCY',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-01-21T12:35:25.560776-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp2',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.14.2.4',
                                                                                                     'pathid': '23',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '24',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'arcos-openconfig-policy-types:ADJACENCY',
                                                                                 'pref': 1,
                                                                                 'protocol-name': 'adjacency',
                                                                                 'tag': 1}},
                                                               'prefix': '10.14.2.4/32'},
                                              '10.14.3.0/24': {'best-protocol': 'DIRECTLY_CONNECTED',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-02-06T13:21:27.409772-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'GLEAN',
                                                                                                     'interface': 'swp3',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.14.3.1',
                                                                                                     'pathid': '614',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '615',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'DIRECTLY_CONNECTED',
                                                                                 'pref': 0,
                                                                                 'protocol-name': 'directly_connected',
                                                                                 'tag': 0}},
                                                               'prefix': '10.14.3.0/24'},
                                              '10.14.3.1/32': {'best-protocol': 'DIRECTLY_CONNECTED',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-02-06T13:21:27.409811-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'LOCAL',
                                                                                                     'interface': 'swp3',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.14.3.1',
                                                                                                     'pathid': '616',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '617',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'DIRECTLY_CONNECTED',
                                                                                 'pref': 0,
                                                                                 'protocol-name': 'directly_connected',
                                                                                 'tag': 0}},
                                                               'prefix': '10.14.3.1/32'},
                                              '10.14.3.4/32': {'best-protocol': 'arcos-openconfig-policy-types:ADJACENCY',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-02-06T13:21:31.101216-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp3',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.14.3.4',
                                                                                                     'pathid': '622',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '623',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'arcos-openconfig-policy-types:ADJACENCY',
                                                                                 'pref': 1,
                                                                                 'protocol-name': 'adjacency',
                                                                                 'tag': 1}},
                                                               'prefix': '10.14.3.4/32'},
                                              '10.15.4.0/24': {'best-protocol': 'DIRECTLY_CONNECTED',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-02-06T13:21:27.503241-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'GLEAN',
                                                                                                     'interface': 'swp4',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.15.4.1',
                                                                                                     'pathid': '618',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '619',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'DIRECTLY_CONNECTED',
                                                                                 'pref': 0,
                                                                                 'protocol-name': 'directly_connected',
                                                                                 'tag': 0}},
                                                               'prefix': '10.15.4.0/24'},
                                              '10.15.4.1/32': {'best-protocol': 'DIRECTLY_CONNECTED',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-02-06T13:21:27.503278-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'LOCAL',
                                                                                                     'interface': 'swp4',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.15.4.1',
                                                                                                     'pathid': '620',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '621',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'DIRECTLY_CONNECTED',
                                                                                 'pref': 0,
                                                                                 'protocol-name': 'directly_connected',
                                                                                 'tag': 0}},
                                                               'prefix': '10.15.4.1/32'},
                                              '10.15.4.5/32': {'best-protocol': 'arcos-openconfig-policy-types:ADJACENCY',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'last-updated': '2026-02-06T13:21:31.196224-00:00',
                                                                                 'metric': 1,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp4',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.15.4.5',
                                                                                                     'pathid': '624',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '625',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'arcos-openconfig-policy-types:ADJACENCY',
                                                                                 'pref': 1,
                                                                                 'protocol-name': 'adjacency',
                                                                                 'tag': 1}},
                                                               'prefix': '10.15.4.5/32'},
                                              '10.23.2.0/24': {'best-protocol': 'ISIS',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'label-pref': 114,
                                                                                 'last-updated': '2026-02-18T06:48:20.616286-00:00',
                                                                                 'metric': 20,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp1',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.12.1.2',
                                                                                                     'pathid': '440',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '441',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'ISIS',
                                                                                 'pref': 115,
                                                                                 'protocol-name': 'isis-default@default',
                                                                                 'route-type': 'ISIS_L2',
                                                                                 'tag': 0}},
                                                               'prefix': '10.23.2.0/24'},
                                              '10.24.4.0/24': {'best-protocol': 'ISIS',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'label-pref': 114,
                                                                                 'last-updated': '2026-02-18T06:48:20.616483-00:00',
                                                                                 'metric': 20,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp3',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.14.3.4',
                                                                                                     'pathid': '622',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100},
                                                                                               '1': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp2',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.14.2.4',
                                                                                                     'pathid': '23',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100},
                                                                                               '2': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp1',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.12.1.2',
                                                                                                     'pathid': '440',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '633',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'ISIS',
                                                                                 'pref': 115,
                                                                                 'protocol-name': 'isis-default@default',
                                                                                 'route-type': 'ISIS_L2',
                                                                                 'tag': 0}},
                                                               'prefix': '10.24.4.0/24'},
                                              '10.25.5.0/24': {'best-protocol': 'ISIS',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'label-pref': 114,
                                                                                 'last-updated': '2026-02-18T06:48:20.615173-00:00',
                                                                                 'metric': 20,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp4',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.15.4.5',
                                                                                                     'pathid': '624',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100},
                                                                                               '1': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp1',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.12.1.2',
                                                                                                     'pathid': '440',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '631',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'ISIS',
                                                                                 'pref': 115,
                                                                                 'protocol-name': 'isis-default@default',
                                                                                 'route-type': 'ISIS_L2',
                                                                                 'tag': 0}},
                                                               'prefix': '10.25.5.0/24'},
                                              '10.26.3.0/24': {'best-protocol': 'ISIS',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'label-pref': 114,
                                                                                 'last-updated': '2026-02-18T06:48:20.616721-00:00',
                                                                                 'metric': 20,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp1',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.12.1.2',
                                                                                                     'pathid': '440',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '441',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'ISIS',
                                                                                 'pref': 115,
                                                                                 'protocol-name': 'isis-default@default',
                                                                                 'route-type': 'ISIS_L2',
                                                                                 'tag': 0}},
                                                               'prefix': '10.26.3.0/24'},
                                              '10.35.3.0/24': {'best-protocol': 'ISIS',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'label-pref': 114,
                                                                                 'last-updated': '2026-02-18T06:48:20.616153-00:00',
                                                                                 'metric': 20,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp4',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.15.4.5',
                                                                                                     'pathid': '624',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '625',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'ISIS',
                                                                                 'pref': 115,
                                                                                 'protocol-name': 'isis-default@default',
                                                                                 'route-type': 'ISIS_L2',
                                                                                 'tag': 0}},
                                                               'prefix': '10.35.3.0/24'},
                                              '10.36.1.0/24': {'best-protocol': 'ISIS',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'label-pref': 114,
                                                                                 'last-updated': '2026-02-18T06:48:20.616812-00:00',
                                                                                 'metric': 30,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp4',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.15.4.5',
                                                                                                     'pathid': '624',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100},
                                                                                               '1': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp1',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.12.1.2',
                                                                                                     'pathid': '440',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '631',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'ISIS',
                                                                                 'pref': 115,
                                                                                 'protocol-name': 'isis-default@default',
                                                                                 'route-type': 'ISIS_L2',
                                                                                 'tag': 0}},
                                                               'prefix': '10.36.1.0/24'},
                                              '10.36.4.0/24': {'best-protocol': 'ISIS',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'label-pref': 114,
                                                                                 'last-updated': '2026-02-18T06:48:20.616892-00:00',
                                                                                 'metric': 30,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp4',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.15.4.5',
                                                                                                     'pathid': '624',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100},
                                                                                               '1': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp1',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.12.1.2',
                                                                                                     'pathid': '440',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '631',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'ISIS',
                                                                                 'pref': 115,
                                                                                 'protocol-name': 'isis-default@default',
                                                                                 'route-type': 'ISIS_L2',
                                                                                 'tag': 0}},
                                                               'prefix': '10.36.4.0/24'},
                                              '10.45.1.0/24': {'best-protocol': 'ISIS',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'label-pref': 114,
                                                                                 'last-updated': '2026-02-18T06:48:20.615651-00:00',
                                                                                 'metric': 20,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp4',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.15.4.5',
                                                                                                     'pathid': '624',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100},
                                                                                               '1': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp3',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.14.3.4',
                                                                                                     'pathid': '622',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100},
                                                                                               '2': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp2',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.14.2.4',
                                                                                                     'pathid': '23',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '632',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'ISIS',
                                                                                 'pref': 115,
                                                                                 'protocol-name': 'isis-default@default',
                                                                                 'route-type': 'ISIS_L2',
                                                                                 'tag': 0}},
                                                               'prefix': '10.45.1.0/24'},
                                              '10.56.2.0/24': {'best-protocol': 'ISIS',
                                                               'hw-update': {'install-ack': False,
                                                                             'status-code': 0,
                                                                             'version': '0'},
                                                               'origins': {'0': {'flags': '',
                                                                                 'label-pref': 114,
                                                                                 'last-updated': '2026-02-18T06:48:20.616218-00:00',
                                                                                 'metric': 20,
                                                                                 'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                     'interface': 'swp4',
                                                                                                     'network-instance': 'default',
                                                                                                     'next-hop': '10.15.4.5',
                                                                                                     'pathid': '624',
                                                                                                     'type': 'IPV4',
                                                                                                     'weight': 100}},
                                                                                 'nhid': '625',
                                                                                 'opaque-data': '0',
                                                                                 'origin-protocol': 'ISIS',
                                                                                 'pref': 115,
                                                                                 'protocol-name': 'isis-default@default',
                                                                                 'route-type': 'ISIS_L2',
                                                                                 'tag': 0}},
                                                               'prefix': '10.56.2.0/24'},
                                              '2.2.2.2/32': {'best-protocol': 'ISIS',
                                                             'hw-update': {'install-ack': False,
                                                                           'status-code': 0,
                                                                           'version': '0'},
                                                             'origins': {'0': {'flags': '',
                                                                               'label-pref': 114,
                                                                               'last-updated': '2026-03-08T10:25:58.742726-00:00',
                                                                               'metric': 20,
                                                                               'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                   'interface': 'swp1',
                                                                                                   'network-instance': 'default',
                                                                                                   'next-hop': '10.12.1.2',
                                                                                                   'pathid': '634',
                                                                                                   'pushed-mpls-label-stack': [3],
                                                                                                   'type': 'IPV4',
                                                                                                   'weight': 100}},
                                                                               'nhid': '635',
                                                                               'opaque-data': '0',
                                                                               'origin-protocol': 'ISIS',
                                                                               'pref': 115,
                                                                               'protocol-name': 'isis-default@default',
                                                                               'route-type': 'ISIS_L2',
                                                                               'tag': 0}},
                                                             'prefix': '2.2.2.2/32'},
                                              '22.22.22.22/32': {'best-protocol': 'ISIS',
                                                                 'hw-update': {'install-ack': False,
                                                                               'status-code': 0,
                                                                               'version': '0'},
                                                                 'origins': {'0': {'flags': '',
                                                                                   'label-pref': 114,
                                                                                   'last-updated': '2026-02-18T06:48:20.617228-00:00',
                                                                                   'metric': 20,
                                                                                   'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                       'interface': 'swp1',
                                                                                                       'network-instance': 'default',
                                                                                                       'next-hop': '10.12.1.2',
                                                                                                       'pathid': '440',
                                                                                                       'type': 'IPV4',
                                                                                                       'weight': 100}},
                                                                                   'nhid': '441',
                                                                                   'opaque-data': '0',
                                                                                   'origin-protocol': 'ISIS',
                                                                                   'pref': 115,
                                                                                   'protocol-name': 'isis-default@default',
                                                                                   'route-type': 'ISIS_L2',
                                                                                   'tag': 0}},
                                                                 'prefix': '22.22.22.22/32'},
                                              '3.3.3.3/32': {'best-protocol': 'ISIS',
                                                             'hw-update': {'install-ack': False,
                                                                           'status-code': 0,
                                                                           'version': '0'},
                                                             'origins': {'0': {'flags': '',
                                                                               'label-pref': 114,
                                                                               'last-updated': '2026-02-18T06:48:20.617053-00:00',
                                                                               'metric': 30,
                                                                               'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                   'interface': 'swp4',
                                                                                                   'network-instance': 'default',
                                                                                                   'next-hop': '10.15.4.5',
                                                                                                   'pathid': '624',
                                                                                                   'type': 'IPV4',
                                                                                                   'weight': 100},
                                                                                             '1': {'flags': 'ATTACH',
                                                                                                   'interface': 'swp1',
                                                                                                   'network-instance': 'default',
                                                                                                   'next-hop': '10.12.1.2',
                                                                                                   'pathid': '440',
                                                                                                   'type': 'IPV4',
                                                                                                   'weight': 100}},
                                                                               'nhid': '631',
                                                                               'opaque-data': '0',
                                                                               'origin-protocol': 'ISIS',
                                                                               'pref': 115,
                                                                               'protocol-name': 'isis-default@default',
                                                                               'route-type': 'ISIS_L2',
                                                                               'tag': 0}},
                                                             'prefix': '3.3.3.3/32'},
                                              '4.4.4.4/32': {'best-protocol': 'ISIS',
                                                             'hw-update': {'install-ack': False,
                                                                           'status-code': 0,
                                                                           'version': '0'},
                                                             'origins': {'0': {'flags': 'ECMP_FEC_OPTIMIZE',
                                                                               'label-pref': 114,
                                                                               'last-updated': '2026-03-08T10:25:58.742571-00:00',
                                                                               'metric': 20,
                                                                               'next-hops': {'0': {'flags': 'RECURSIVE '
                                                                                                            'IGP_NH',
                                                                                                   'network-instance': 'default',
                                                                                                   'next-hop': 630,
                                                                                                   'pathid': '640',
                                                                                                   'pushed-mpls-label-stack': [3],
                                                                                                   'type': 'IGP',
                                                                                                   'weight': 100}},
                                                                               'nhid': '641',
                                                                               'opaque-data': '0',
                                                                               'origin-protocol': 'ISIS',
                                                                               'pref': 115,
                                                                               'protocol-name': 'isis-default@default',
                                                                               'route-type': 'ISIS_L2',
                                                                               'tag': 0}},
                                                             'prefix': '4.4.4.4/32'},
                                              '5.5.5.5/32': {'best-protocol': 'ISIS',
                                                             'hw-update': {'install-ack': False,
                                                                           'status-code': 0,
                                                                           'version': '0'},
                                                             'origins': {'0': {'flags': '',
                                                                               'label-pref': 114,
                                                                               'last-updated': '2026-03-08T10:25:58.742977-00:00',
                                                                               'metric': 20,
                                                                               'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                   'interface': 'swp4',
                                                                                                   'network-instance': 'default',
                                                                                                   'next-hop': '10.15.4.5',
                                                                                                   'pathid': '642',
                                                                                                   'pushed-mpls-label-stack': [3],
                                                                                                   'type': 'IPV4',
                                                                                                   'weight': 100}},
                                                                               'nhid': '643',
                                                                               'opaque-data': '0',
                                                                               'origin-protocol': 'ISIS',
                                                                               'pref': 115,
                                                                               'protocol-name': 'isis-default@default',
                                                                               'route-type': 'ISIS_L2',
                                                                               'tag': 0}},
                                                             'prefix': '5.5.5.5/32'},
                                              '55.55.55.55/32': {'best-protocol': 'ISIS',
                                                                 'hw-update': {'install-ack': False,
                                                                               'status-code': 0,
                                                                               'version': '0'},
                                                                 'origins': {'0': {'flags': '',
                                                                                   'label-pref': 114,
                                                                                   'last-updated': '2026-02-18T06:48:20.616078-00:00',
                                                                                   'metric': 20,
                                                                                   'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                       'interface': 'swp4',
                                                                                                       'network-instance': 'default',
                                                                                                       'next-hop': '10.15.4.5',
                                                                                                       'pathid': '624',
                                                                                                       'type': 'IPV4',
                                                                                                       'weight': 100}},
                                                                                   'nhid': '625',
                                                                                   'opaque-data': '0',
                                                                                   'origin-protocol': 'ISIS',
                                                                                   'pref': 115,
                                                                                   'protocol-name': 'isis-default@default',
                                                                                   'route-type': 'ISIS_L2',
                                                                                   'tag': 0}},
                                                                 'prefix': '55.55.55.55/32'},
                                              '6.6.6.6/32': {'best-protocol': 'ISIS',
                                                             'hw-update': {'install-ack': False,
                                                                           'status-code': 0,
                                                                           'version': '0'},
                                                             'origins': {'0': {'flags': '',
                                                                               'label-pref': 114,
                                                                               'last-updated': '2026-02-18T06:48:20.617151-00:00',
                                                                               'metric': 30,
                                                                               'next-hops': {'0': {'flags': 'ATTACH',
                                                                                                   'interface': 'swp4',
                                                                                                   'network-instance': 'default',
                                                                                                   'next-hop': '10.15.4.5',
                                                                                                   'pathid': '624',
                                                                                                   'type': 'IPV4',
                                                                                                   'weight': 100},
                                                                                             '1': {'flags': 'ATTACH',
                                                                                                   'interface': 'swp1',
                                                                                                   'network-instance': 'default',
                                                                                                   'next-hop': '10.12.1.2',
                                                                                                   'pathid': '440',
                                                                                                   'type': 'IPV4',
                                                                                                   'weight': 100}},
                                                                               'nhid': '631',
                                                                               'opaque-data': '0',
                                                                               'origin-protocol': 'ISIS',
                                                                               'pref': 115,
                                                                               'protocol-name': 'isis-default@default',
                                                                               'route-type': 'ISIS_L2',
                                                                               'tag': 0}},
                                                             'prefix': '6.6.6.6/32'}}}}}
