expected_output = {'areas': {'0': {'lsa-types': {'ROUTER_LSA': {'type': 'ROUTER_LSA',
                                              'lsas': {'1.1.1.1:1.1.1.1': {'link-state-id': '1.1.1.1',
                                                                           'advertising-router': '1.1.1.1',
                                                                           'sequence-number': '80:00:00:03',
                                                                           'checksum': 58494,
                                                                           'age': 77,
                                                                           'router-lsa': {'num-links': 3,
                                                                                          'links': {'0': {'type': 'ROUTER_LSA_P2P',
                                                                                                          'link-id': '2.2.2.2',
                                                                                                          'link-data': '10.12.1.1',
                                                                                                          'metric': 320},
                                                                                                    '1': {'type': 'ROUTER_LSA_STUB_NETWORK',
                                                                                                          'link-id': '10.12.1.0',
                                                                                                          'link-data': '255.255.255.0',
                                                                                                          'metric': 320},
                                                                                                    '2': {'type': 'ROUTER_LSA_STUB_NETWORK',
                                                                                                          'link-id': '1.1.1.1',
                                                                                                          'link-data': '255.255.255.255',
                                                                                                          'metric': 10}}}},
                                                       '2.2.2.2:2.2.2.2': {'link-state-id': '2.2.2.2',
                                                                           'advertising-router': '2.2.2.2',
                                                                           'sequence-number': '80:00:00:04',
                                                                           'checksum': 2128,
                                                                           'age': 76,
                                                                           'router-lsa': {'flags': 'B',
                                                                                          'num-links': 3,
                                                                                          'links': {'0': {'type': 'ROUTER_LSA_P2P',
                                                                                                          'link-id': '1.1.1.1',
                                                                                                          'link-data': '10.12.1.2',
                                                                                                          'metric': 320},
                                                                                                    '1': {'type': 'ROUTER_LSA_STUB_NETWORK',
                                                                                                          'link-id': '10.12.1.0',
                                                                                                          'link-data': '255.255.255.0',
                                                                                                          'metric': 320},
                                                                                                    '2': {'type': 'ROUTER_LSA_STUB_NETWORK',
                                                                                                          'link-id': '2.2.2.2',
                                                                                                          'link-data': '255.255.255.255',
                                                                                                          'metric': 10}}}}}},
                               'NETWORK_LSA': {'type': 'NETWORK_LSA'},
                               'SUMMARY_IP_NETWORK_LSA': {'type': 'SUMMARY_IP_NETWORK_LSA',
                                                          'lsas': {'10.23.2.0:2.2.2.2': {'link-state-id': '10.23.2.0',
                                                                                         'advertising-router': '2.2.2.2',
                                                                                         'sequence-number': '80:00:00:01',
                                                                                         'checksum': 3555,
                                                                                         'age': 118,
                                                                                         'summary-lsa': {'network-mask': 24,
                                                                                                         'metric': 320}},
                                                                   '22.22.22.22:2.2.2.2': {'link-state-id': '22.22.22.22',
                                                                                           'advertising-router': '2.2.2.2',
                                                                                           'sequence-number': '80:00:00:01',
                                                                                           'checksum': 39767,
                                                                                           'age': 122,
                                                                                           'summary-lsa': {'network-mask': 32,
                                                                                                           'metric': 10}}}},
                               'SUMMARY_ASBR_LSA': {'type': 'SUMMARY_ASBR_LSA'}}},
           '1': {'lsa-types': {'ROUTER_LSA': {'type': 'ROUTER_LSA',
                                              'lsas': {'2.2.2.2:2.2.2.2': {'link-state-id': '2.2.2.2',
                                                                           'advertising-router': '2.2.2.2',
                                                                           'sequence-number': '80:00:00:04',
                                                                           'checksum': 8393,
                                                                           'age': 52,
                                                                           'router-lsa': {'flags': 'B',
                                                                                          'num-links': 3,
                                                                                          'links': {'0': {'type': 'ROUTER_LSA_P2P',
                                                                                                          'link-id': '3.3.3.3',
                                                                                                          'link-data': '10.23.2.2',
                                                                                                          'metric': 320},
                                                                                                    '1': {'type': 'ROUTER_LSA_STUB_NETWORK',
                                                                                                          'link-id': '10.23.2.0',
                                                                                                          'link-data': '255.255.255.0',
                                                                                                          'metric': 320},
                                                                                                    '2': {'type': 'ROUTER_LSA_STUB_NETWORK',
                                                                                                          'link-id': '22.22.22.22',
                                                                                                          'link-data': '255.255.255.255',
                                                                                                          'metric': 10}}}},
                                                       '3.3.3.3:3.3.3.3': {'link-state-id': '3.3.3.3',
                                                                           'advertising-router': '3.3.3.3',
                                                                           'sequence-number': '80:00:00:03',
                                                                           'checksum': 3876,
                                                                           'age': 53,
                                                                           'router-lsa': {'num-links': 3,
                                                                                          'links': {'0': {'type': 'ROUTER_LSA_P2P',
                                                                                                          'link-id': '2.2.2.2',
                                                                                                          'link-data': '10.23.2.3',
                                                                                                          'metric': 320},
                                                                                                    '1': {'type': 'ROUTER_LSA_STUB_NETWORK',
                                                                                                          'link-id': '10.23.2.0',
                                                                                                          'link-data': '255.255.255.0',
                                                                                                          'metric': 320},
                                                                                                    '2': {'type': 'ROUTER_LSA_STUB_NETWORK',
                                                                                                          'link-id': '3.3.3.3',
                                                                                                          'link-data': '255.255.255.255',
                                                                                                          'metric': 10}}}}}},
                               'NETWORK_LSA': {'type': 'NETWORK_LSA'},
                               'SUMMARY_IP_NETWORK_LSA': {'type': 'SUMMARY_IP_NETWORK_LSA',
                                                          'lsas': {'0.0.0.0:2.2.2.2': {'link-state-id': '0.0.0.0',
                                                                                       'advertising-router': '2.2.2.2',
                                                                                       'sequence-number': '80:00:00:02',
                                                                                       'checksum': 44956,
                                                                                       'age': 125,
                                                                                       'summary-lsa': {'network-mask': 0,
                                                                                                       'metric': 10}},
                                                                   '2.2.2.2:2.2.2.2': {'link-state-id': '2.2.2.2',
                                                                                       'advertising-router': '2.2.2.2',
                                                                                       'sequence-number': '80:00:00:01',
                                                                                       'checksum': 21999,
                                                                                       'age': 124,
                                                                                       'summary-lsa': {'network-mask': 32,
                                                                                                       'metric': 10}},
                                                                   '10.12.1.0:2.2.2.2': {'link-state-id': '10.12.1.0',
                                                                                         'advertising-router': '2.2.2.2',
                                                                                         'sequence-number': '80:00:00:01',
                                                                                         'checksum': 47684,
                                                                                         'age': 124,
                                                                                         'summary-lsa': {'network-mask': 24,
                                                                                                         'metric': 320}}}},
                               'SUMMARY_ASBR_LSA': {'type': 'SUMMARY_ASBR_LSA'}}}}}
