expected_output = {'network-instance': {'default': {'isis': {'default': {'interfaces': {'swp1': {'enabled': True,
                                                                               'interface_id': 'swp1',
                                                                               'passive': False,
                                                                               'hello_padding': 'STRICT',
                                                                               'circuit_type': 'LEVEL_2',
                                                                               'network_type': 'POINT_TO_POINT',
                                                                               'protocol_up': True,
                                                                               'snpa': 'f2:d2:c6:b5:9e:a6',
                                                                               'mtu': 8974,
                                                                               'ifindex': 332,
                                                                               'update_index': 1,
                                                                               'speed': 10,
                                                                               'circuit_counters': {'adj_changes': 1,
                                                                                                    'init_fails': 0,
                                                                                                    'rejected_adj': 0,
                                                                                                    'id_field_len_mismatches': 0,
                                                                                                    'max_area_address_mismatches': 0,
                                                                                                    'auth_type_fails': 0,
                                                                                                    'auth_fails': 0,
                                                                                                    'lan_dis_changes': 0,
                                                                                                    'adj_number': 1,
                                                                                                    'subnet_mismatches': 0,
                                                                                                    'duplicate_addresses': 0,
                                                                                                    'martian_addresses': 0,
                                                                                                    'missing_addresses': 0},
                                                                               'authentication': {'hello_authentication': True,
                                                                                                  'auth_type': 'SIMPLE_KEY',
                                                                                                  'crypto_algorithm': 'MD5'},
                                                                               'afi_safi': {'IPV6_UNICAST': {'afi_name': 'IPV6',
                                                                                                             'safi_name': 'UNICAST',
                                                                                                             'enabled': True,
                                                                                                             'fast_reroute': {'ip_enabled': False,
                                                                                                                              'ti_lfa_srv6_enabled': True,
                                                                                                                              'ti_lfa_sr_mpls_enabled': False}}},
                                                                               'timers': {'csnp_interval': 10,
                                                                                          'lsp_pacing_interval': 33,
                                                                                          'hello_interval': 10,
                                                                                          'hello_multiplier': 3},
                                                                               'bfd': {'bfd_tlv': False,
                                                                                       'profile': ''},
                                                                               'fast_reroute': {'srv6_enabled': True,
                                                                                                'tiebreakers': {'srlg_disjoint': {'priority': 10},
                                                                                                                'node_protecting': {'priority': 20}}},
                                                                               'csnp_enabled': True,
                                                                               'mpls_ldp_sync_enabled': False,
                                                                               'levels': {'2': {'enabled': True,
                                                                                                'priority': 64,
                                                                                                'metric': 1000000,
                                                                                                'flexible_algorithm': {'te_metric': 1000000,
                                                                                                                       'delay_metric': 1000000},
                                                                                                'packet_counters': {'lsp': {'received': 4626,
                                                                                                                            'processed': 4624,
                                                                                                                            'dropped': 0,
                                                                                                                            'sent': 1070,
                                                                                                                            'retransmit': 0,
                                                                                                                            'no_memory': 0},
                                                                                                                    'iih': {'received': 31946,
                                                                                                                            'processed': 31946,
                                                                                                                            'dropped': 0,
                                                                                                                            'sent': 31997,
                                                                                                                            'retransmit': 0},
                                                                                                                    'psnp': {'received': 1065,
                                                                                                                             'processed': 1065,
                                                                                                                             'dropped': 0,
                                                                                                                             'sent': 4512,
                                                                                                                             'retransmit': 0},
                                                                                                                    'csnp': {'received': 1,
                                                                                                                             'processed': 1,
                                                                                                                             'dropped': 0,
                                                                                                                             'sent': 1,
                                                                                                                             'retransmit': 0},
                                                                                                                    'unknown': {'received': 0,
                                                                                                                                'dropped': 0}},
                                                                                                'hello_authentication': {'hello_authentication': True,
                                                                                                                         'auth_type': 'SIMPLE_KEY',
                                                                                                                         'crypto_algorithm': 'MD5'},
                                                                                                'adjacencies': {'zr11': {'system_id': 'zr11',
                                                                                                                         'neighbor_ipv6_address': 'fe80::1',
                                                                                                                         'local_extended_circuit_id': 332,
                                                                                                                         'neighbor_extended_circuit_id': 333,
                                                                                                                         'neighbor_circuit_type': 'LEVEL_2',
                                                                                                                         'adjacency_type': 'LEVEL_2',
                                                                                                                         'adjacency_state': 'UP',
                                                                                                                         'remaining_hold_time': 26,
                                                                                                                         'up_time': 27988988,
                                                                                                                         'restart_support': True,
                                                                                                                         'restart_suppress': False,
                                                                                                                         'restart_status': False,
                                                                                                                         'nlpid': ['IPV6'],
                                                                                                                         'usable': True,
                                                                                                                         'restart_ack': False,
                                                                                                                         'restart_request': False,
                                                                                                                         'received_multi_topology_ids': ['ISIS_MT_ID2_IPV6_UNICAST'],
                                                                                                                         'active_multi_topology_ids': ['ISIS_MT_ID2_IPV6_UNICAST'],
                                                                                                                         'bfd': {'bfd_required': False,
                                                                                                                                 'topologies': {0: {'mt_id': 0,
                                                                                                                                                    'ipv4_bfd_required': False,
                                                                                                                                                    'bfd_required': False,
                                                                                                                                                    'ipv4_bfd_up': False,
                                                                                                                                                    'ipv4_up': False,
                                                                                                                                                    'usable': False},
                                                                                                                                                2: {'mt_id': 2,
                                                                                                                                                    'ipv6_bfd_required': False,
                                                                                                                                                    'bfd_required': False,
                                                                                                                                                    'ipv6_bfd_up': False,
                                                                                                                                                    'ipv6_up': True,
                                                                                                                                                    'usable': True}}},
                                                                                                                         'dynamic_delay_measurement': {'enabled': False,
                                                                                                                                                       'num_advertisements_sent': 0,
                                                                                                                                                       'last_sampled_avg_delay_value': 0,
                                                                                                                                                       'last_advertised_min_delay_value': 0,
                                                                                                                                                       'last_advertised_max_delay_value': 0,
                                                                                                                                                       'last_advertised_timestamp': '1969-12-31T16:00:00+00:00',
                                                                                                                                                       'last_advertisement_reason': ''}}}}}},
                                                                      'swp2': {'enabled': True,
                                                                               'interface_id': 'swp2',
                                                                               'passive': False,
                                                                               'hello_padding': 'STRICT',
                                                                               'circuit_type': 'LEVEL_2',
                                                                               'network_type': 'POINT_TO_POINT',
                                                                               'protocol_up': True,
                                                                               'snpa': 'd6:41:cb:dd:87:68',
                                                                               'mtu': 8974,
                                                                               'ifindex': 343,
                                                                               'update_index': 2,
                                                                               'speed': 10,
                                                                               'circuit_counters': {'adj_changes': 1,
                                                                                                    'init_fails': 0,
                                                                                                    'rejected_adj': 0,
                                                                                                    'id_field_len_mismatches': 0,
                                                                                                    'max_area_address_mismatches': 0,
                                                                                                    'auth_type_fails': 0,
                                                                                                    'auth_fails': 0,
                                                                                                    'lan_dis_changes': 0,
                                                                                                    'adj_number': 1,
                                                                                                    'subnet_mismatches': 0,
                                                                                                    'duplicate_addresses': 0,
                                                                                                    'martian_addresses': 0,
                                                                                                    'missing_addresses': 0},
                                                                               'authentication': {'hello_authentication': True,
                                                                                                  'auth_type': 'SIMPLE_KEY',
                                                                                                  'crypto_algorithm': 'MD5'},
                                                                               'afi_safi': {'IPV6_UNICAST': {'afi_name': 'IPV6',
                                                                                                             'safi_name': 'UNICAST',
                                                                                                             'enabled': True,
                                                                                                             'fast_reroute': {'ip_enabled': False,
                                                                                                                              'ti_lfa_srv6_enabled': True,
                                                                                                                              'ti_lfa_sr_mpls_enabled': False}}},
                                                                               'timers': {'csnp_interval': 10,
                                                                                          'lsp_pacing_interval': 33,
                                                                                          'hello_interval': 10,
                                                                                          'hello_multiplier': 3},
                                                                               'bfd': {'bfd_tlv': False,
                                                                                       'profile': ''},
                                                                               'fast_reroute': {'srv6_enabled': True,
                                                                                                'tiebreakers': {'srlg_disjoint': {'priority': 10},
                                                                                                                'node_protecting': {'priority': 20}}},
                                                                               'csnp_enabled': True,
                                                                               'mpls_ldp_sync_enabled': False,
                                                                               'levels': {'2': {'enabled': True,
                                                                                                'priority': 64,
                                                                                                'metric': 11000,
                                                                                                'flexible_algorithm': {'te_metric': 11000,
                                                                                                                       'delay_metric': 11000},
                                                                                                'packet_counters': {'lsp': {'received': 3562,
                                                                                                                            'processed': 3560,
                                                                                                                            'dropped': 0,
                                                                                                                            'sent': 2232,
                                                                                                                            'retransmit': 0,
                                                                                                                            'no_memory': 0},
                                                                                                                    'iih': {'received': 31990,
                                                                                                                            'processed': 31990,
                                                                                                                            'dropped': 0,
                                                                                                                            'sent': 32005,
                                                                                                                            'retransmit': 0},
                                                                                                                    'psnp': {'received': 2202,
                                                                                                                             'processed': 2202,
                                                                                                                             'dropped': 0,
                                                                                                                             'sent': 3489,
                                                                                                                             'retransmit': 0},
                                                                                                                    'csnp': {'received': 1,
                                                                                                                             'processed': 1,
                                                                                                                             'dropped': 0,
                                                                                                                             'sent': 1,
                                                                                                                             'retransmit': 0},
                                                                                                                    'unknown': {'received': 0,
                                                                                                                                'dropped': 0}},
                                                                                                'hello_authentication': {'hello_authentication': True,
                                                                                                                         'auth_type': 'SIMPLE_KEY',
                                                                                                                         'crypto_algorithm': 'MD5'},
                                                                                                'adjacencies': {'mp02': {'system_id': 'mp02',
                                                                                                                         'neighbor_ipv6_address': 'fe80::1',
                                                                                                                         'local_extended_circuit_id': 343,
                                                                                                                         'neighbor_extended_circuit_id': 342,
                                                                                                                         'neighbor_circuit_type': 'LEVEL_2',
                                                                                                                         'adjacency_type': 'LEVEL_2',
                                                                                                                         'adjacency_state': 'UP',
                                                                                                                         'remaining_hold_time': 24,
                                                                                                                         'up_time': 27988995,
                                                                                                                         'restart_support': True,
                                                                                                                         'restart_suppress': False,
                                                                                                                         'restart_status': False,
                                                                                                                         'nlpid': ['IPV6'],
                                                                                                                         'usable': True,
                                                                                                                         'restart_ack': False,
                                                                                                                         'restart_request': False,
                                                                                                                         'received_multi_topology_ids': ['ISIS_MT_ID2_IPV6_UNICAST'],
                                                                                                                         'active_multi_topology_ids': ['ISIS_MT_ID2_IPV6_UNICAST'],
                                                                                                                         'bfd': {'bfd_required': False,
                                                                                                                                 'topologies': {0: {'mt_id': 0,
                                                                                                                                                    'ipv4_bfd_required': False,
                                                                                                                                                    'bfd_required': False,
                                                                                                                                                    'ipv4_bfd_up': False,
                                                                                                                                                    'ipv4_up': False,
                                                                                                                                                    'usable': False},
                                                                                                                                                2: {'mt_id': 2,
                                                                                                                                                    'ipv6_bfd_required': False,
                                                                                                                                                    'bfd_required': False,
                                                                                                                                                    'ipv6_bfd_up': False,
                                                                                                                                                    'ipv6_up': True,
                                                                                                                                                    'usable': True}}},
                                                                                                                         'dynamic_delay_measurement': {'enabled': False,
                                                                                                                                                       'num_advertisements_sent': 0,
                                                                                                                                                       'last_sampled_avg_delay_value': 0,
                                                                                                                                                       'last_advertised_min_delay_value': 0,
                                                                                                                                                       'last_advertised_max_delay_value': 0,
                                                                                                                                                       'last_advertised_timestamp': '1969-12-31T16:00:00+00:00',
                                                                                                                                                       'last_advertisement_reason': ''}}}}}},
                                                                      'swp3': {'enabled': True,
                                                                               'interface_id': 'swp3',
                                                                               'passive': False,
                                                                               'hello_padding': 'STRICT',
                                                                               'circuit_type': 'LEVEL_1',
                                                                               'network_type': 'POINT_TO_POINT',
                                                                               'protocol_up': True,
                                                                               'snpa': '32:fb:5f:51:28:06',
                                                                               'mtu': 9100,
                                                                               'ifindex': 345,
                                                                               'update_index': 3,
                                                                               'speed': 10,
                                                                               'circuit_counters': {'adj_changes': 1,
                                                                                                    'init_fails': 0,
                                                                                                    'rejected_adj': 0,
                                                                                                    'id_field_len_mismatches': 0,
                                                                                                    'max_area_address_mismatches': 0,
                                                                                                    'auth_type_fails': 0,
                                                                                                    'auth_fails': 0,
                                                                                                    'lan_dis_changes': 0,
                                                                                                    'adj_number': 1,
                                                                                                    'subnet_mismatches': 0,
                                                                                                    'duplicate_addresses': 0,
                                                                                                    'martian_addresses': 0,
                                                                                                    'missing_addresses': 0},
                                                                               'authentication': {'hello_authentication': True,
                                                                                                  'auth_type': 'SIMPLE_KEY',
                                                                                                  'crypto_algorithm': 'MD5'},
                                                                               'afi_safi': {'IPV6_UNICAST': {'afi_name': 'IPV6',
                                                                                                             'safi_name': 'UNICAST',
                                                                                                             'enabled': True,
                                                                                                             'fast_reroute': {'ip_enabled': False,
                                                                                                                              'ti_lfa_srv6_enabled': True,
                                                                                                                              'ti_lfa_sr_mpls_enabled': False}}},
                                                                               'timers': {'csnp_interval': 10,
                                                                                          'lsp_pacing_interval': 33,
                                                                                          'hello_interval': 10,
                                                                                          'hello_multiplier': 3},
                                                                               'bfd': {'bfd_tlv': False,
                                                                                       'profile': ''},
                                                                               'fast_reroute': {'srv6_enabled': True,
                                                                                                'tiebreakers': {'srlg_disjoint': {'priority': 10},
                                                                                                                'node_protecting': {'priority': 20}}},
                                                                               'csnp_enabled': True,
                                                                               'mpls_ldp_sync_enabled': False,
                                                                               'levels': {'1': {'enabled': True,
                                                                                                'priority': 64,
                                                                                                'metric': 100,
                                                                                                'flexible_algorithm': {'te_metric': 100,
                                                                                                                       'delay_metric': 100},
                                                                                                'packet_counters': {'lsp': {'received': 3209,
                                                                                                                            'processed': 3207,
                                                                                                                            'dropped': 0,
                                                                                                                            'sent': 538,
                                                                                                                            'retransmit': 0,
                                                                                                                            'no_memory': 0},
                                                                                                                    'iih': {'received': 31990,
                                                                                                                            'processed': 31990,
                                                                                                                            'dropped': 0,
                                                                                                                            'sent': 31991,
                                                                                                                            'retransmit': 0},
                                                                                                                    'psnp': {'received': 538,
                                                                                                                             'processed': 538,
                                                                                                                             'dropped': 0,
                                                                                                                             'sent': 3188,
                                                                                                                             'retransmit': 0},
                                                                                                                    'csnp': {'received': 1,
                                                                                                                             'processed': 1,
                                                                                                                             'dropped': 0,
                                                                                                                             'sent': 1,
                                                                                                                             'retransmit': 0},
                                                                                                                    'unknown': {'received': 0,
                                                                                                                                'dropped': 0}},
                                                                                                'hello_authentication': {'hello_authentication': True,
                                                                                                                         'auth_type': 'SIMPLE_KEY',
                                                                                                                         'crypto_algorithm': 'MD5'},
                                                                                                'adjacencies': {'leaf4': {'system_id': 'leaf4',
                                                                                                                          'neighbor_ipv6_address': 'fe80::2',
                                                                                                                          'local_extended_circuit_id': 345,
                                                                                                                          'neighbor_extended_circuit_id': 344,
                                                                                                                          'neighbor_circuit_type': 'LEVEL_1',
                                                                                                                          'adjacency_type': 'LEVEL_1',
                                                                                                                          'adjacency_state': 'UP',
                                                                                                                          'remaining_hold_time': 24,
                                                                                                                          'up_time': 27989004,
                                                                                                                          'restart_support': True,
                                                                                                                          'restart_suppress': False,
                                                                                                                          'restart_status': False,
                                                                                                                          'nlpid': ['IPV6'],
                                                                                                                          'usable': True,
                                                                                                                          'restart_ack': False,
                                                                                                                          'restart_request': False,
                                                                                                                          'received_multi_topology_ids': ['ISIS_MT_ID2_IPV6_UNICAST'],
                                                                                                                          'active_multi_topology_ids': ['ISIS_MT_ID2_IPV6_UNICAST'],
                                                                                                                          'bfd': {'bfd_required': False,
                                                                                                                                  'topologies': {0: {'mt_id': 0,
                                                                                                                                                     'ipv4_bfd_required': False,
                                                                                                                                                     'bfd_required': False,
                                                                                                                                                     'ipv4_bfd_up': False,
                                                                                                                                                     'ipv4_up': False,
                                                                                                                                                     'usable': False},
                                                                                                                                                 2: {'mt_id': 2,
                                                                                                                                                     'ipv6_bfd_required': False,
                                                                                                                                                     'bfd_required': False,
                                                                                                                                                     'ipv6_bfd_up': False,
                                                                                                                                                     'ipv6_up': True,
                                                                                                                                                     'usable': True}}},
                                                                                                                          'dynamic_delay_measurement': {'enabled': False,
                                                                                                                                                        'num_advertisements_sent': 0,
                                                                                                                                                        'last_sampled_avg_delay_value': 0,
                                                                                                                                                        'last_advertised_min_delay_value': 0,
                                                                                                                                                        'last_advertised_max_delay_value': 0,
                                                                                                                                                        'last_advertised_timestamp': '1969-12-31T16:00:00+00:00',
                                                                                                                                                        'last_advertisement_reason': ''}}}}}},
                                                                      'loopback0': {'enabled': True,
                                                                                    'interface_id': 'loopback0',
                                                                                    'passive': False,
                                                                                    'hello_padding': 'STRICT',
                                                                                    'circuit_type': 'LEVEL_1_2',
                                                                                    'network_type': 'LOOPBACK',
                                                                                    'protocol_up': True,
                                                                                    'snpa': '52:a1:6b:d1:09:ac',
                                                                                    'mtu': 8974,
                                                                                    'ifindex': 20005,
                                                                                    'update_index': 0,
                                                                                    'speed': 0,
                                                                                    'authentication': {'hello_authentication': False,
                                                                                                       'auth_type': 'SIMPLE_KEY',
                                                                                                       'crypto_algorithm': 'CRYPTO_TYPE'},
                                                                                    'afi_safi': {'IPV6_UNICAST': {'afi_name': 'IPV6',
                                                                                                                  'safi_name': 'UNICAST',
                                                                                                                  'enabled': True,
                                                                                                                  'fast_reroute': {'ip_enabled': False,
                                                                                                                                   'ti_lfa_srv6_enabled': False,
                                                                                                                                   'ti_lfa_sr_mpls_enabled': False}}},
                                                                                    'bfd': {'bfd_tlv': False,
                                                                                            'profile': ''},
                                                                                    'fast_reroute': {'srv6_enabled': False,
                                                                                                     'tiebreakers': {'srlg_disjoint': {'priority': 10},
                                                                                                                     'node_protecting': {'priority': 20}}},
                                                                                    'csnp_enabled': True,
                                                                                    'mpls_ldp_sync_enabled': False,
                                                                                    'levels': {'1': {'enabled': True,
                                                                                                     'priority': 64,
                                                                                                     'metric': 10,
                                                                                                     'hello_authentication': {'hello_authentication': False,
                                                                                                                              'auth_type': 'SIMPLE_KEY',
                                                                                                                              'crypto_algorithm': 'CRYPTO_TYPE'}},
                                                                                               '2': {'enabled': True,
                                                                                                     'priority': 64,
                                                                                                     'metric': 10,
                                                                                                     'hello_authentication': {'hello_authentication': False,
                                                                                                                              'auth_type': 'SIMPLE_KEY',
                                                                                                                              'crypto_algorithm': 'CRYPTO_TYPE'}}}}}}}}}}
