expected_output = {'network-instance': {'default': {'isis': {'default': {'interfaces': {'swp1': {'enabled': True,
                                                                               'interface_id': 'swp1',
                                                                               'passive': False,
                                                                               'hello_padding': 'STRICT',
                                                                               'circuit_type': 'LEVEL_2',
                                                                               'network_type': 'POINT_TO_POINT',
                                                                               'protocol_up': True,
                                                                               'snpa': '6e:80:ef:da:2f:14',
                                                                               'mtu': 8974,
                                                                               'afi_safi': {'IPV4_UNICAST': {'afi_name': 'IPV4',
                                                                                                             'safi_name': 'UNICAST',
                                                                                                             'enabled': True,
                                                                                                             'ipv4_unnumbered': False,
                                                                                                             'fast_reroute': {'ip_enabled': False,
                                                                                                                              'ti_lfa_sr_mpls_enabled': True}},
                                                                                            'IPV6_UNICAST': {'afi_name': 'IPV6',
                                                                                                             'safi_name': 'UNICAST',
                                                                                                             'enabled': True,
                                                                                                             'fast_reroute': {'ip_enabled': False,
                                                                                                                              'ti_lfa_srv6_enabled': True,
                                                                                                                              'ti_lfa_sr_mpls_enabled': False}}},
                                                                               'flexible_algorithm': {'admin_groups': ['blue',
                                                                                                                       'green',
                                                                                                                       'red']},
                                                                               'csnp_enabled': True,
                                                                               'mpls_ldp_sync_enabled': False,
                                                                               'levels': {'2': {'enabled': True,
                                                                                                'priority': 64,
                                                                                                'metric': 10,
                                                                                                'adjacencies': {'rtr1': {'system_id': 'rtr1',
                                                                                                                         'neighbor_ipv4_address': '10.20.0.10',
                                                                                                                         'local_extended_circuit_id': 757,
                                                                                                                         'neighbor_extended_circuit_id': 758,
                                                                                                                         'neighbor_circuit_type': 'LEVEL_2',
                                                                                                                         'adjacency_type': 'LEVEL_2',
                                                                                                                         'adjacency_state': 'UP',
                                                                                                                         'remaining_hold_time': 28,
                                                                                                                         'up_time': 15574,
                                                                                                                         'restart_support': False,
                                                                                                                         'restart_status': False,
                                                                                                                         'nlpid': ['IPV4'],
                                                                                                                         'adjacency_up_time': '0d '
                                                                                                                                              '04:19:34',
                                                                                                                         'num_state_changes': 2,
                                                                                                                         'last_state_change_timestamp': '2025-12-03T06:30:00.123456+00:00',
                                                                                                                         'last_down_reason': 'HOLD_TIME',
                                                                                                                         'usable': True,
                                                                                                                         'bfd': {'bfd_required': False,
                                                                                                                                 'topologies': {0: {'mt_id': 0,
                                                                                                                                                    'ipv4_bfd_required': False,
                                                                                                                                                    'bfd_required': False,
                                                                                                                                                    'ipv4_bfd_up': False,
                                                                                                                                                    'ipv4_up': True,
                                                                                                                                                    'usable': True}}},
                                                                                                                         'dynamic_delay_measurement': {'enabled': True,
                                                                                                                                                       'num_advertisements_sent': 5,
                                                                                                                                                       'last_sampled_avg_delay_value': 150,
                                                                                                                                                       'last_advertised_min_delay_value': 120,
                                                                                                                                                       'last_advertised_max_delay_value': 180,
                                                                                                                                                       'last_advertised_timestamp': '2025-12-03T10:30:00.000000+00:00',
                                                                                                                                                       'last_advertisement_reason': 'threshold-exceeded'}}}}}},
                                                                      'loopback0': {'enabled': True,
                                                                                    'interface_id': 'loopback0',
                                                                                    'passive': False,
                                                                                    'hello_padding': 'STRICT',
                                                                                    'circuit_type': 'LEVEL_2',
                                                                                    'network_type': 'LOOPBACK',
                                                                                    'protocol_up': True,
                                                                                    'levels': {'2': {'enabled': True,
                                                                                                     'priority': 64,
                                                                                                     'metric': 10}}}}}}}}}
