expected_output = {'neighbors': {'1.1.1.1/0': {'auth-enable': False,
                             'label-space-id': 0,
                             'lsr-id': '1.1.1.1',
                             'maximum-remote-binding': 0,
                             'targeted-address-families': {'IPV4': {'afi-name': 'IPV4',
                                                                    'destination-address': '1.1.1.1',
                                                                    'enabled': True}},
                             'targeted-hello-holdtime': 45,
                             'targeted-hello-interval': 15},
               '3.3.3.3/0': {'auth-enable': False,
                             'label-space-id': 0,
                             'lsr-id': '3.3.3.3',
                             'maximum-remote-binding': 0,
                             'targeted-address-families': {'IPV4': {'afi-name': 'IPV4',
                                                                    'destination-address': '3.3.3.3',
                                                                    'enabled': True}},
                             'targeted-hello-holdtime': 45,
                             'targeted-hello-interval': 15}}}
