expected_output = {'vlans': {'2001': {'members': ['swp5.6001'],
                    'name': '',
                    'status': 'ACTIVE',
                    'vlan-id': 2001},
           '2002': {'members': ['swp5.6002'],
                    'name': '',
                    'status': 'ACTIVE',
                    'vlan-id': 2002},
           '2501': {'members': ['swp7'],
                    'name': '',
                    'status': 'ACTIVE',
                    'vlan-id': 2501},
           '3500': {'name': '', 'status': 'ACTIVE', 'vlan-id': 3500},
           '3502': {'members': ['swp5.8001'],
                    'name': '',
                    'status': 'ACTIVE',
                    'vlan-id': 3502},
           '3503': {'name': '', 'status': 'ACTIVE', 'vlan-id': 3503},
           '3700': {'members': ['swp29.6001'],
                    'name': '',
                    'status': 'ACTIVE',
                    'vlan-id': 3700},
           '3701': {'members': ['swp29.6002'],
                    'name': '',
                    'status': 'ACTIVE',
                    'vlan-id': 3701},
           '3702': {'members': ['swp29.6003'],
                    'name': '',
                    'status': 'ACTIVE',
                    'vlan-id': 3702},
           '3703': {'members': ['swp29.6004'],
                    'name': '',
                    'status': 'ACTIVE',
                    'vlan-id': 3703},
           '3704': {'members': ['swp29.6005'],
                    'name': '',
                    'status': 'ACTIVE',
                    'vlan-id': 3704},
           '3963': {'name': '', 'status': 'ACTIVE', 'vlan-id': 3963},
           '9': {'name': '', 'status': 'ACTIVE', 'vlan-id': 9}}}
