expected_output = {'network-instance': {'default': {'isis': {'default': {'flex-algo-routes': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                             'safi-name': 'UNICAST',
                                                                                             'algorithms': {'131': {'id': 131,
                                                                                                                    'routes': {'2400:2020:31:2291::/64': {'prefix': '2400:2020:31:2291::/64',
                                                                                                                                                          'best-level-number': 2,
                                                                                                                                                          'levels': {'2': {'level-number': 2,
                                                                                                                                                                           'metric': 104,
                                                                                                                                                                           'flags': ['remote',
                                                                                                                                                                                     'srv6-locator',
                                                                                                                                                                                     'best'],
                                                                                                                                                                           'next-hop-id': '2147483726',
                                                                                                                                                                           'prefix-origin-count': 1,
                                                                                                                                                                           'route-tag': 0,
                                                                                                                                                                           'last-updated-time': '2025-11-27T07:51:08.880472+00:00',
                                                                                                                                                                           'next-hops': [{'next-hop-address': 'fe80::6c80:efff:feda:2f14',
                                                                                                                                                                                          'outgoing-interface': 'swp1'}]}}}}},
                                                                                                            '132': {'id': 132,
                                                                                                                    'routes': {'2400:2020:32:2291::/64': {'prefix': '2400:2020:32:2291::/64',
                                                                                                                                                          'best-level-number': 2,
                                                                                                                                                          'levels': {'2': {'level-number': 2,
                                                                                                                                                                           'metric': 20,
                                                                                                                                                                           'flags': ['remote',
                                                                                                                                                                                     'srv6-locator',
                                                                                                                                                                                     'best'],
                                                                                                                                                                           'next-hop-id': '2147483723',
                                                                                                                                                                           'prefix-origin-count': 1,
                                                                                                                                                                           'route-tag': 0,
                                                                                                                                                                           'last-updated-time': '2025-11-27T01:40:37.406236+00:00',
                                                                                                                                                                           'next-hops': [{'next-hop-address': 'fe80::6c80:efff:feda:2f14',
                                                                                                                                                                                          'outgoing-interface': 'swp1'},
                                                                                                                                                                                         {'next-hop-address': '::',
                                                                                                                                                                                          'outgoing-interface': 'swp4',
                                                                                                                                                                                          'tunnel-id': '268435457',
                                                                                                                                                                                          'backup': True}]}}},
                                                                                                                               '2400:2020:32:3391::/64': {'prefix': '2400:2020:32:3391::/64',
                                                                                                                                                          'best-level-number': 2,
                                                                                                                                                          'levels': {'2': {'level-number': 2,
                                                                                                                                                                           'metric': 20,
                                                                                                                                                                           'flags': ['remote',
                                                                                                                                                                                     'srv6-locator',
                                                                                                                                                                                     'best'],
                                                                                                                                                                           'next-hop-id': '2147483722',
                                                                                                                                                                           'prefix-origin-count': 1,
                                                                                                                                                                           'route-tag': 0,
                                                                                                                                                                           'last-updated-time': '2025-11-27T01:40:37.405997+00:00',
                                                                                                                                                                           'next-hops': [{'next-hop-address': 'fe80::2c66:19ff:fecf:2b01',
                                                                                                                                                                                          'outgoing-interface': 'swp4'},
                                                                                                                                                                                         {'next-hop-address': 'fe80::6c80:efff:feda:2f14',
                                                                                                                                                                                          'outgoing-interface': 'swp1',
                                                                                                                                                                                          'backup': True}]}}}}}}}}}}}}}
