expected_output = {'network-instance': {'default': {'isis': {'default': {'redistribute-routes': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                'safi-name': 'UNICAST',
                                                                                                'routes': {'1:1:1::1/128': {'prefix': '1:1:1::1/128',
                                                                                                                            'levels': {'2': {'level-number': 2,
                                                                                                                                             'metric': 10,
                                                                                                                                             'route-tag': 0,
                                                                                                                                             'flags': ['connected'],
                                                                                                                                             'source-identifier': 'ISIS',
                                                                                                                                             'source-name': 'default@default'}}},
                                                                                                           '10:20::/120': {'prefix': '10:20::/120',
                                                                                                                           'levels': {'2': {'level-number': 2,
                                                                                                                                            'metric': 10,
                                                                                                                                            'route-tag': 0,
                                                                                                                                            'flags': ['connected'],
                                                                                                                                            'source-identifier': 'ISIS',
                                                                                                                                            'source-name': 'default@default'}}}}},
                                                                               'IPV4-UNICAST': {'afi-name': 'IPV4',
                                                                                                'safi-name': 'UNICAST',
                                                                                                'routes': {'1.1.1.1/32': {'prefix': '1.1.1.1/32',
                                                                                                                          'levels': {'2': {'level-number': 2,
                                                                                                                                           'metric': 10,
                                                                                                                                           'route-tag': 0,
                                                                                                                                           'flags': ['connected'],
                                                                                                                                           'source-identifier': 'ISIS',
                                                                                                                                           'source-name': 'default@default'}}},
                                                                                                           '10.20.0.0/24': {'prefix': '10.20.0.0/24',
                                                                                                                            'levels': {'2': {'level-number': 2,
                                                                                                                                             'metric': 10,
                                                                                                                                             'route-tag': 0,
                                                                                                                                             'flags': ['connected'],
                                                                                                                                             'source-identifier': 'ISIS',
                                                                                                                                             'source-name': 'default@default'}}}}}}}}}}}
