expected_output = {'network-instance': {'default': {'isis': {'default': {'redistribute-routes': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                'safi-name': 'UNICAST',
                                                                                                'routes': {'2400:2020:0:100::/56': {'prefix': '2400:2020:0:100::/56',
                                                                                                                                    'levels': {'2': {'level-number': 2,
                                                                                                                                                     'metric': 110,
                                                                                                                                                     'route-tag': 0,
                                                                                                                                                     'flags': ['summary'],
                                                                                                                                                     'source-identifier': 'ISIS',
                                                                                                                                                     'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:102::/64': {'prefix': '2400:2020:0:102::/64',
                                                                                                                                    'levels': {'2': {'level-number': 2,
                                                                                                                                                     'metric': 110,
                                                                                                                                                     'route-tag': 0,
                                                                                                                                                     'flags': ['distribute'],
                                                                                                                                                     'source-identifier': 'ISIS',
                                                                                                                                                     'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:102::1/128': {'prefix': '2400:2020:0:102::1/128',
                                                                                                                                      'levels': {'2': {'level-number': 2,
                                                                                                                                                       'metric': 110,
                                                                                                                                                       'route-tag': 0,
                                                                                                                                                       'flags': ['distribute'],
                                                                                                                                                       'source-identifier': 'ISIS',
                                                                                                                                                       'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:201::/64': {'prefix': '2400:2020:0:201::/64',
                                                                                                                                    'levels': {'1': {'level-number': 1,
                                                                                                                                                     'metric': 1005010,
                                                                                                                                                     'route-tag': 69,
                                                                                                                                                     'flags': ['distribute',
                                                                                                                                                               'down'],
                                                                                                                                                     'source-identifier': 'ISIS',
                                                                                                                                                     'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:201::1/128': {'prefix': '2400:2020:0:201::1/128',
                                                                                                                                      'levels': {'1': {'level-number': 1,
                                                                                                                                                       'metric': 1005010,
                                                                                                                                                       'route-tag': 69,
                                                                                                                                                       'flags': ['distribute',
                                                                                                                                                                 'down'],
                                                                                                                                                       'source-identifier': 'ISIS',
                                                                                                                                                       'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:900::/56': {'prefix': '2400:2020:0:900::/56',
                                                                                                                                    'levels': {'1': {'level-number': 1,
                                                                                                                                                     'metric': 10,
                                                                                                                                                     'route-tag': 100,
                                                                                                                                                     'flags': ['summary'],
                                                                                                                                                     'source-identifier': 'ISIS',
                                                                                                                                                     'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:901::/64': {'prefix': '2400:2020:0:901::/64',
                                                                                                                                    'levels': {'1': {'level-number': 1,
                                                                                                                                                     'metric': 1002810,
                                                                                                                                                     'route-tag': 69,
                                                                                                                                                     'flags': ['distribute',
                                                                                                                                                               'down'],
                                                                                                                                                     'source-identifier': 'ISIS',
                                                                                                                                                     'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:901::1/128': {'prefix': '2400:2020:0:901::1/128',
                                                                                                                                      'levels': {'1': {'level-number': 1,
                                                                                                                                                       'metric': 1002810,
                                                                                                                                                       'route-tag': 69,
                                                                                                                                                       'flags': ['distribute',
                                                                                                                                                                 'down'],
                                                                                                                                                       'source-identifier': 'ISIS',
                                                                                                                                                       'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:902::/64': {'prefix': '2400:2020:0:902::/64',
                                                                                                                                    'levels': {'1': {'level-number': 1,
                                                                                                                                                     'metric': 1000010,
                                                                                                                                                     'route-tag': 69,
                                                                                                                                                     'flags': ['distribute',
                                                                                                                                                               'down'],
                                                                                                                                                     'source-identifier': 'ISIS',
                                                                                                                                                     'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:902::1/128': {'prefix': '2400:2020:0:902::1/128',
                                                                                                                                      'levels': {'1': {'level-number': 1,
                                                                                                                                                       'metric': 1001500,
                                                                                                                                                       'route-tag': 69,
                                                                                                                                                       'flags': ['distribute',
                                                                                                                                                                 'down'],
                                                                                                                                                       'source-identifier': 'ISIS',
                                                                                                                                                       'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:903::/64': {'prefix': '2400:2020:0:903::/64',
                                                                                                                                    'levels': {'1': {'level-number': 1,
                                                                                                                                                     'metric': 1005310,
                                                                                                                                                     'route-tag': 69,
                                                                                                                                                     'flags': ['distribute',
                                                                                                                                                               'down'],
                                                                                                                                                     'source-identifier': 'ISIS',
                                                                                                                                                     'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:903::1/128': {'prefix': '2400:2020:0:903::1/128',
                                                                                                                                      'levels': {'1': {'level-number': 1,
                                                                                                                                                       'metric': 1005310,
                                                                                                                                                       'route-tag': 69,
                                                                                                                                                       'flags': ['distribute',
                                                                                                                                                                 'down'],
                                                                                                                                                       'source-identifier': 'ISIS',
                                                                                                                                                       'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:905::/64': {'prefix': '2400:2020:0:905::/64',
                                                                                                                                    'levels': {'1': {'level-number': 1,
                                                                                                                                                     'metric': 10,
                                                                                                                                                     'route-tag': 0,
                                                                                                                                                     'flags': ['redistribute'],
                                                                                                                                                     'source-identifier': 'arcos-SIDMGR'},
                                                                                                                                               '2': {'level-number': 2,
                                                                                                                                                     'metric': 10,
                                                                                                                                                     'route-tag': 0,
                                                                                                                                                     'flags': ['redistribute'],
                                                                                                                                                     'source-identifier': 'arcos-SIDMGR'}}},
                                                                                                           '2400:2020:0:905::1/128': {'prefix': '2400:2020:0:905::1/128',
                                                                                                                                      'levels': {'1': {'level-number': 1,
                                                                                                                                                       'metric': 10,
                                                                                                                                                       'route-tag': 69,
                                                                                                                                                       'flags': ['connected'],
                                                                                                                                                       'source-identifier': 'ISIS',
                                                                                                                                                       'source-name': 'default@default'},
                                                                                                                                                 '2': {'level-number': 2,
                                                                                                                                                       'metric': 10,
                                                                                                                                                       'route-tag': 0,
                                                                                                                                                       'flags': ['connected'],
                                                                                                                                                       'source-identifier': 'ISIS',
                                                                                                                                                       'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:906::1/128': {'prefix': '2400:2020:0:906::1/128',
                                                                                                                                      'levels': {'1': {'level-number': 1,
                                                                                                                                                       'metric': 11010,
                                                                                                                                                       'route-tag': 69,
                                                                                                                                                       'flags': ['distribute',
                                                                                                                                                                 'down'],
                                                                                                                                                       'source-identifier': 'ISIS',
                                                                                                                                                       'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:908::/64': {'prefix': '2400:2020:0:908::/64',
                                                                                                                                    'levels': {'1': {'level-number': 1,
                                                                                                                                                     'metric': 6000010,
                                                                                                                                                     'route-tag': 69,
                                                                                                                                                     'flags': ['distribute',
                                                                                                                                                               'down'],
                                                                                                                                                     'source-identifier': 'ISIS',
                                                                                                                                                     'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:908::1/128': {'prefix': '2400:2020:0:908::1/128',
                                                                                                                                      'levels': {'1': {'level-number': 1,
                                                                                                                                                       'metric': 6000010,
                                                                                                                                                       'route-tag': 69,
                                                                                                                                                       'flags': ['distribute',
                                                                                                                                                                 'down'],
                                                                                                                                                       'source-identifier': 'ISIS',
                                                                                                                                                       'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:909::/64': {'prefix': '2400:2020:0:909::/64',
                                                                                                                                    'levels': {'1': {'level-number': 1,
                                                                                                                                                     'metric': 1002510,
                                                                                                                                                     'route-tag': 69,
                                                                                                                                                     'flags': ['distribute',
                                                                                                                                                               'down'],
                                                                                                                                                     'source-identifier': 'ISIS',
                                                                                                                                                     'source-name': 'default@default'}}},
                                                                                                           '2400:2020:0:909::1/128': {'prefix': '2400:2020:0:909::1/128',
                                                                                                                                      'levels': {'1': {'level-number': 1,
                                                                                                                                                       'metric': 1002510,
                                                                                                                                                       'route-tag': 69,
                                                                                                                                                       'flags': ['distribute',
                                                                                                                                                                 'down'],
                                                                                                                                                       'source-identifier': 'ISIS',
                                                                                                                                                       'source-name': 'default@default'}}}}}}}}}}}
