expected_output = {'loopback0': {'name': 'loopback0',
               'type': 'iana-if-type:softwareLoopback',
               'mtu': 9000,
               'enabled': True,
               'admin-status': 'UP',
               'oper-status': 'UP',
               'description': '',
               'last-change': '2025-11-26T06:26:16.869171-00:00',
               'counters': {'in-octets': '0',
                            'in-unicast-pkts': '0',
                            'in-errors': '0',
                            'out-octets': '0',
                            'out-unicast-pkts': '0',
                            'out-errors': '0'},
               'ipv6-addresses': {'1::1': {'ip': '1::1', 'prefix-length': 128}}}}
