expected_output = {'areas': {'0': {'identifier': 0,
                 'area-type': 'AREA_TYPE_NORMAL',
                 'advertise-summary-lsas': True,
                 'stub-default-cost': 1,
                 'configured-interface-count': 2,
                 'up-interface-count': 2,
                 'neighbor-count': 1,
                 'exchange-neighbor-count': 0,
                 'loading-neighbor-count': 0,
                 'full-neighbor-count': 1},
           '1': {'identifier': 1,
                 'area-type': 'AREA_TYPE_STUB',
                 'advertise-summary-lsas': True,
                 'stub-default-cost': 10,
                 'configured-interface-count': 2,
                 'up-interface-count': 2,
                 'neighbor-count': 1,
                 'exchange-neighbor-count': 0,
                 'loading-neighbor-count': 0,
                 'full-neighbor-count': 1}}}
