expected_output = {'network-instance': {'default': {'isis': {'default': {'interface': {'swp1': {'level': {2: {'adjacency': {'rtr1': {'state': 'UP',
                                                                                                                   'holdtime': 28,
                                                                                                                   'adjacency-type': 'LEVEL_2',
                                                                                                                   'neighbor-ipv4-address': '10.20.0.10',
                                                                                                                   'neighbor-ipv6-address': 'fe80::1',
                                                                                                                   'up-time': 429525,
                                                                                                                   'local-extended-circuit-id': 757,
                                                                                                                   'neighbor-extended-circuit-id': 758,
                                                                                                                   'neighbor-circuit-type': 'LEVEL_2',
                                                                                                                   'restart-support': True,
                                                                                                                   'restart-suppress': False,
                                                                                                                   'restart-status': False,
                                                                                                                   'nlpid': ['IPV4',
                                                                                                                             'IPV6'],
                                                                                                                   'usable': True,
                                                                                                                   'restart-ack': False,
                                                                                                                   'restart-request': False,
                                                                                                                   'received-multi-topology-ids': ['arcos-openconfig-isis-augments:ISIS_MT_ID2_IPV6_UNICAST'],
                                                                                                                   'active-multi-topology-ids': ['arcos-openconfig-isis-augments:ISIS_MT_ID2_IPV6_UNICAST'],
                                                                                                                   'bfd': {'bfd-required': False,
                                                                                                                           'topologies': {0: {'mt-id': 0,
                                                                                                                                              'ipv4-bfd-required': False,
                                                                                                                                              'bfd-required': False,
                                                                                                                                              'ipv4-bfd-up': False,
                                                                                                                                              'ipv4-up': True,
                                                                                                                                              'usable': True},
                                                                                                                                          2: {'mt-id': 2,
                                                                                                                                              'ipv6-bfd-required': False,
                                                                                                                                              'bfd-required': False,
                                                                                                                                              'ipv6-bfd-up': False,
                                                                                                                                              'ipv6-up': True,
                                                                                                                                              'usable': True}}},
                                                                                                                   'dynamic-delay-measurement': {'enabled': False,
                                                                                                                                                 'num-advertisements-sent': 0,
                                                                                                                                                 'last-sampled-avg-delay-value': 0,
                                                                                                                                                 'last-advertised-min-delay-value': 0,
                                                                                                                                                 'last-advertised-max-delay-value': 0,
                                                                                                                                                 'last-advertised-timestamp': '1969-12-31T16:00:00+00:00',
                                                                                                                                                 'last-advertisement-reason': ''}}}}}}}}}}}}
