expected_output = {'policies': {'ingress-policy': {'classifiers': {'class-default': {'actions': [{'rate_unit': 'bps',
                                                                                'rate_value': 5000000,
                                                                                'type': 'RATE_MAX'},
                                                                               {'rate_unit': 'bps',
                                                                                'rate_value': 500000,
                                                                                'type': 'RATE_MIN'},
                                                                               {'ratio': 50,
                                                                                'type': 'RATE_EXCESS'}],
                                                                   'name': 'class-default'},
                                                 'class-voice': {'actions': [{'burst_unit': 'bytes',
                                                                              'burst_value': 4096,
                                                                              'rate_unit': 'bps',
                                                                              'rate_value': 1000000,
                                                                              'type': 'POLICE'},
                                                                             {'level': 1,
                                                                              'type': 'PRIORITY'},
                                                                             {'local_tc': 7,
                                                                              'type': 'MARKING'}],
                                                                 'description': 'Voice traffic',
                                                                 'name': 'class-voice'}},
                                 'name': 'ingress-policy'}}}
