expected_output = {'network-instance': {'default': {'isis': {'default': {'routes': {'IPV4-UNICAST': {'afi-name': 'IPV4',
                                                                                   'safi-name': 'UNICAST',
                                                                                   'routes': {'1.1.1.1/32': {'prefix': '1.1.1.1/32',
                                                                                                             'best-level-number': 2,
                                                                                                             'levels': {'2': {'level-number': 2,
                                                                                                                              'metric': 10,
                                                                                                                              'flags': ['connected',
                                                                                                                                        'best'],
                                                                                                                              'prefix-origin-count': 1,
                                                                                                                              'route-tag': 0,
                                                                                                                              'last-updated-time': '2025-11-21T08:10:32.140586+00:00',
                                                                                                                              'next-hops': [{'next-hop-address': '0.0.0.0',
                                                                                                                                             'outgoing-interface': 'loopback0'}]}}},
                                                                                              '2.2.2.2/32': {'prefix': '2.2.2.2/32',
                                                                                                             'best-level-number': 2,
                                                                                                             'levels': {'2': {'level-number': 2,
                                                                                                                              'metric': 20,
                                                                                                                              'flags': ['remote',
                                                                                                                                        'best'],
                                                                                                                              'next-hop-id': '2147483649',
                                                                                                                              'prefix-origin-count': 1,
                                                                                                                              'route-tag': 0,
                                                                                                                              'last-updated-time': '2025-11-21T08:10:49.811374+00:00',
                                                                                                                              'next-hops': [{'next-hop-address': '10.20.0.20',
                                                                                                                                             'outgoing-interface': 'swp1'}]}}}}},
                                                                  'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                   'safi-name': 'UNICAST',
                                                                                   'routes': {'1:1:1::1/128': {'prefix': '1:1:1::1/128',
                                                                                                               'best-level-number': 2,
                                                                                                               'levels': {'2': {'level-number': 2,
                                                                                                                                'metric': 10,
                                                                                                                                'flags': ['connected',
                                                                                                                                          'best'],
                                                                                                                                'prefix-origin-count': 1,
                                                                                                                                'route-tag': 0,
                                                                                                                                'last-updated-time': '2025-11-21T08:10:32.140619+00:00',
                                                                                                                                'next-hops': [{'next-hop-address': '::',
                                                                                                                                               'outgoing-interface': 'loopback0'}]}}},
                                                                                              '2:2:2::2/128': {'prefix': '2:2:2::2/128',
                                                                                                               'best-level-number': 2,
                                                                                                               'levels': {'2': {'level-number': 2,
                                                                                                                                'metric': 20,
                                                                                                                                'flags': ['remote',
                                                                                                                                          'best'],
                                                                                                                                'next-hop-id': '2147483652',
                                                                                                                                'prefix-origin-count': 1,
                                                                                                                                'route-tag': 0,
                                                                                                                                'last-updated-time': '2025-11-21T08:10:49.811578+00:00',
                                                                                                                                'next-hops': [{'next-hop-address': 'fe80::6c80:efff:feda:2f14',
                                                                                                                                               'outgoing-interface': 'swp1'}]}}}}}}}}}}}
