expected_output = {'global': {'router-id': '2.2.2.2',
            'route-preference': {'intra-area': 110, 'inter-area': 115, 'external': 120}},
 'areas': {'0': {'identifier': 0,
                 'interfaces': {'loopback0': {'id': 'loopback0'},
                                'swp1': {'id': 'swp1',
                                         'network-type': 'POINT_TO_POINT_NETWORK',
                                         'hello-interval': 10,
                                         'dead-interval': 40}}},
           '1': {'identifier': 1,
                 'area-type': 'AREA_TYPE_STUB',
                 'stub-default-cost': 10,
                 'interfaces': {'loopback1': {'id': 'loopback1'},
                                'swp2': {'id': 'swp2',
                                         'network-type': 'POINT_TO_POINT_NETWORK',
                                         'hello-interval': 10,
                                         'dead-interval': 40}}}}}
