expected_output = {'network-instance': {'default': {'address-family': 'IPV6',
                                  'label-entries': {'10101': {'control-word': False,
                                                              'domain-name': '',
                                                              'flow-label': False,
                                                              'local-label': 10101,
                                                              'vpn-table-id': 2147483649},
                                                    '10102': {'local-label': 10102,
                                                              'next-hop-id': 268435888,
                                                              'publish-id': 805306799,
                                                              'vpn-table-id': 2147483649},
                                                    '10104': {'local-label': 10104,
                                                              'next-hop-id': 268435892,
                                                              'publish-id': 805306803,
                                                              'vpn-table-id': 2147483649},
                                                    '10105': {'local-label': 10105,
                                                              'next-hop-id': 268435890,
                                                              'publish-id': 805306801,
                                                              'vpn-table-id': 2147483649}}}}}
