expected_output = {'network-instance': {'default': {'address-family': 'IPV4',
                                  'label-entries': {'10001': {'control-word': False,
                                                              'domain-name': '',
                                                              'flow-label': False,
                                                              'local-label': 10001,
                                                              'vpn-table-id': 1},
                                                    '10002': {'local-label': 10002,
                                                              'next-hop-id': 635,
                                                              'publish-id': 536871546,
                                                              'vpn-table-id': 1},
                                                    '10004': {'local-label': 10004,
                                                              'next-hop-id': 641,
                                                              'publish-id': 536871552,
                                                              'vpn-table-id': 1},
                                                    '10005': {'local-label': 10005,
                                                              'next-hop-id': 643,
                                                              'publish-id': 536871554,
                                                              'vpn-table-id': 1},
                                                    '20121': {'local-label': 20121,
                                                              'next-hop-id': 635,
                                                              'publish-id': 536871546,
                                                              'vpn-table-id': 1},
                                                    '20141': {'local-label': 20141,
                                                              'next-hop-id': 637,
                                                              'publish-id': 536871548,
                                                              'vpn-table-id': 1},
                                                    '21441': {'local-label': 21441,
                                                              'next-hop-id': 639,
                                                              'publish-id': 536871550,
                                                              'vpn-table-id': 1}}}}}
