expected_output = {'areas': {'0.0.0.0': {'lsa-types': {'NETWORK_LSA': {'lsa-type': 'NETWORK_LSA',
                                                     'lsas': {'0.0.0.10:2.2.2.2': {'advertising-router': '2.2.2.2',
                                                                                   'link-state-id': '0.0.0.10',
                                                                                   'ls-age': 86,
                                                                                   'ls-checksum': 5876,
                                                                                   'ls-sequence-number': '80:00:00:01'}}},
                                     'OSPFV3_INTRA_AREA_PREFIX_LSA': {'lsa-type': 'OSPFV3_INTRA_AREA_PREFIX_LSA',
                                                                      'lsas': {'0.0.0.10:2.2.2.2': {'advertising-router': '2.2.2.2',
                                                                                                    'link-state-id': '0.0.0.10',
                                                                                                    'ls-age': 86,
                                                                                                    'ls-checksum': 10367,
                                                                                                    'ls-sequence-number': '80:00:00:02'}}},
                                     'ROUTER_LSA': {'lsa-type': 'ROUTER_LSA',
                                                    'lsas': {'0.0.0.0:1.1.1.1': {'advertising-router': '1.1.1.1',
                                                                                 'link-state-id': '0.0.0.0',
                                                                                 'ls-age': 85,
                                                                                 'ls-checksum': 48639,
                                                                                 'ls-sequence-number': '80:00:00:01'},
                                                             '0.0.0.0:2.2.2.2': {'advertising-router': '2.2.2.2',
                                                                                 'link-state-id': '0.0.0.0',
                                                                                 'ls-age': 86,
                                                                                 'ls-checksum': 37161,
                                                                                 'ls-sequence-number': '80:00:00:01'}}}}}}}
