expected_output = {'network-instance': {'default': {'address-family': 'IPV4',
                                  'prefix-entries': {'0.0.0.0/0': {'last-updated': '1970-01-01T00:00:00-00:00',
                                                                   'prefix': '0.0.0.0/0'},
                                                     '1.1.1.1/32': {'last-updated': '2026-01-27T17:30:52.547748-00:00',
                                                                    'next-hop-id': 230,
                                                                    'prefix': '1.1.1.1/32',
                                                                    'publish-id': 229,
                                                                    'publish-type': 'PATH'},
                                                     '10.12.1.0/24': {'last-updated': '2026-02-02T20:58:08.59401-00:00',
                                                                      'next-hop-id': 437,
                                                                      'prefix': '10.12.1.0/24',
                                                                      'publish-id': 436,
                                                                      'publish-type': 'PATH'},
                                                     '10.12.1.1/32': {'last-updated': '2026-02-02T20:58:08.594035-00:00',
                                                                      'next-hop-id': 439,
                                                                      'prefix': '10.12.1.1/32',
                                                                      'publish-id': 438,
                                                                      'publish-type': 'PATH'},
                                                     '10.12.1.2/32': {'last-updated': '2026-02-02T20:58:08.659154-00:00',
                                                                      'next-hop-id': 441,
                                                                      'prefix': '10.12.1.2/32',
                                                                      'publish-id': 440,
                                                                      'publish-type': 'PATH'},
                                                     '10.14.2.0/24': {'last-updated': '2026-01-21T12:26:40.100823-00:00',
                                                                      'next-hop-id': 6,
                                                                      'prefix': '10.14.2.0/24',
                                                                      'publish-id': 5,
                                                                      'publish-type': 'PATH'},
                                                     '10.14.2.1/32': {'last-updated': '2026-01-21T12:26:40.100841-00:00',
                                                                      'next-hop-id': 8,
                                                                      'prefix': '10.14.2.1/32',
                                                                      'publish-id': 7,
                                                                      'publish-type': 'PATH'},
                                                     '10.14.2.4/32': {'last-updated': '2026-01-21T12:35:25.561473-00:00',
                                                                      'next-hop-id': 24,
                                                                      'prefix': '10.14.2.4/32',
                                                                      'publish-id': 23,
                                                                      'publish-type': 'PATH'},
                                                     '10.14.3.0/24': {'last-updated': '2026-02-06T13:21:27.410543-00:00',
                                                                      'next-hop-id': 615,
                                                                      'prefix': '10.14.3.0/24',
                                                                      'publish-id': 614,
                                                                      'publish-type': 'PATH'},
                                                     '10.14.3.1/32': {'last-updated': '2026-02-06T13:21:27.410549-00:00',
                                                                      'next-hop-id': 617,
                                                                      'prefix': '10.14.3.1/32',
                                                                      'publish-id': 616,
                                                                      'publish-type': 'PATH'},
                                                     '10.14.3.4/32': {'last-updated': '2026-02-06T13:21:31.10161-00:00',
                                                                      'next-hop-id': 623,
                                                                      'prefix': '10.14.3.4/32',
                                                                      'publish-id': 622,
                                                                      'publish-type': 'PATH'},
                                                     '10.15.4.0/24': {'last-updated': '2026-02-06T13:21:27.503704-00:00',
                                                                      'next-hop-id': 619,
                                                                      'prefix': '10.15.4.0/24',
                                                                      'publish-id': 618,
                                                                      'publish-type': 'PATH'},
                                                     '10.15.4.1/32': {'last-updated': '2026-02-06T13:21:27.503712-00:00',
                                                                      'next-hop-id': 621,
                                                                      'prefix': '10.15.4.1/32',
                                                                      'publish-id': 620,
                                                                      'publish-type': 'PATH'},
                                                     '10.15.4.5/32': {'last-updated': '2026-02-06T13:21:31.196717-00:00',
                                                                      'next-hop-id': 625,
                                                                      'prefix': '10.15.4.5/32',
                                                                      'publish-id': 624,
                                                                      'publish-type': 'PATH'},
                                                     '10.23.2.0/24': {'last-updated': '2026-02-18T06:48:20.618265-00:00',
                                                                      'next-hop-id': 441,
                                                                      'prefix': '10.23.2.0/24',
                                                                      'publish-id': 440,
                                                                      'publish-type': 'PATH'},
                                                     '10.24.4.0/24': {'last-updated': '2026-02-18T06:48:20.618311-00:00',
                                                                      'next-hop-id': 633,
                                                                      'prefix': '10.24.4.0/24',
                                                                      'publish-id': 1073742457,
                                                                      'publish-type': 'ECMP'},
                                                     '10.25.5.0/24': {'last-updated': '2026-02-18T06:48:20.618119-00:00',
                                                                      'next-hop-id': 631,
                                                                      'prefix': '10.25.5.0/24',
                                                                      'publish-id': 1073742455,
                                                                      'publish-type': 'ECMP'},
                                                     '10.26.3.0/24': {'last-updated': '2026-02-18T06:48:20.618329-00:00',
                                                                      'next-hop-id': 441,
                                                                      'prefix': '10.26.3.0/24',
                                                                      'publish-id': 440,
                                                                      'publish-type': 'PATH'},
                                                     '10.35.3.0/24': {'last-updated': '2026-02-18T06:48:20.61823-00:00',
                                                                      'next-hop-id': 625,
                                                                      'prefix': '10.35.3.0/24',
                                                                      'publish-id': 624,
                                                                      'publish-type': 'PATH'},
                                                     '10.36.1.0/24': {'last-updated': '2026-02-18T06:48:20.618347-00:00',
                                                                      'next-hop-id': 631,
                                                                      'prefix': '10.36.1.0/24',
                                                                      'publish-id': 1073742455,
                                                                      'publish-type': 'ECMP'},
                                                     '10.36.4.0/24': {'last-updated': '2026-02-18T06:48:20.618365-00:00',
                                                                      'next-hop-id': 631,
                                                                      'prefix': '10.36.4.0/24',
                                                                      'publish-id': 1073742455,
                                                                      'publish-type': 'ECMP'},
                                                     '10.45.1.0/24': {'last-updated': '2026-02-18T06:48:20.618174-00:00',
                                                                      'next-hop-id': 632,
                                                                      'prefix': '10.45.1.0/24',
                                                                      'publish-id': 1073742456,
                                                                      'publish-type': 'ECMP'},
                                                     '10.56.2.0/24': {'last-updated': '2026-02-18T06:48:20.618248-00:00',
                                                                      'next-hop-id': 625,
                                                                      'prefix': '10.56.2.0/24',
                                                                      'publish-id': 624,
                                                                      'publish-type': 'PATH'},
                                                     '2.2.2.2/32': {'last-updated': '2026-03-08T10:25:58.743887-00:00',
                                                                    'next-hop-id': 635,
                                                                    'prefix': '2.2.2.2/32',
                                                                    'publish-id': 634,
                                                                    'publish-type': 'PATH'},
                                                     '22.22.22.22/32': {'last-updated': '2026-02-18T06:48:20.618499-00:00',
                                                                        'next-hop-id': 441,
                                                                        'prefix': '22.22.22.22/32',
                                                                        'publish-id': 440,
                                                                        'publish-type': 'PATH'},
                                                     '3.3.3.3/32': {'last-updated': '2026-02-18T06:48:20.618458-00:00',
                                                                    'next-hop-id': 631,
                                                                    'prefix': '3.3.3.3/32',
                                                                    'publish-id': 1073742455,
                                                                    'publish-type': 'ECMP'},
                                                     '4.4.4.4/32': {'last-updated': '2026-03-08T10:25:58.743828-00:00',
                                                                    'next-hop-id': 641,
                                                                    'prefix': '4.4.4.4/32',
                                                                    'publish-id': 1073742465,
                                                                    'publish-type': 'ECMP'},
                                                     '5.5.5.5/32': {'last-updated': '2026-03-08T10:25:58.744205-00:00',
                                                                    'next-hop-id': 643,
                                                                    'prefix': '5.5.5.5/32',
                                                                    'publish-id': 642,
                                                                    'publish-type': 'PATH'},
                                                     '55.55.55.55/32': {'last-updated': '2026-02-18T06:48:20.618211-00:00',
                                                                        'next-hop-id': 625,
                                                                        'prefix': '55.55.55.55/32',
                                                                        'publish-id': 624,
                                                                        'publish-type': 'PATH'},
                                                     '6.6.6.6/32': {'last-updated': '2026-02-18T06:48:20.618482-00:00',
                                                                    'next-hop-id': 631,
                                                                    'prefix': '6.6.6.6/32',
                                                                    'publish-id': 1073742455,
                                                                    'publish-type': 'ECMP'}}}}}
