expected_output = {'network-instance': {'Leaf1-Leaf2-EPLAN(M2M)-1': {'bgp': {'afi-safis': ['L2VPN_EVPN'],
                                                           'as': 65002,
                                                           'control-word': True,
                                                           'flow-label': True,
                                                           'label-allocation-mode': 'INSTANCE_LABEL',
                                                           'route-distinguisher': '1.0.0.0:2001',
                                                           'route-targets': [{'route-target': '2001:2001',
                                                                              'route-target-type': 'both'},
                                                                             {'route-target': '3001:3001',
                                                                              'route-target-type': 'import'}],
                                                           'router-id': '1.0.0.0',
                                                           'total-paths': 0,
                                                           'total-prefixes': 0,
                                                           'tunnel-type': 'MPLS',
                                                           'vni-evi': 2001},
                                                   'fdb': {'mac-entries': {'48:0f:cf:af:67:37': {'entry-type': 'DYNAMIC',
                                                                                                 'vlan': 6001},
                                                                           '5c:07:58:74:62:03': {'entry-type': 'DYNAMIC',
                                                                                                 'vlan': 6001}}},
                                                   'interfaces': {'swp5.6001': {'interface': 'swp5',
                                                                                'subinterface': 6001},
                                                                  'swp6.6001': {'interface': 'swp6',
                                                                                'subinterface': 6001}},
                                                   'l2rib': {'advertise-mac-routes': True,
                                                             'id': 2001,
                                                             'is-irb': False,
                                                             'local-label': 2001,
                                                             'mac-count': 1,
                                                             'mac-ipv4-count': 2,
                                                             'maximum-mac-entries': 2048,
                                                             'name': 'Leaf1-Leaf2-EPLAN(M2M)-1',
                                                             'pkt-action': 'FLOOD_ACTION',
                                                             'type': 'TABLE_TYPE_VLAN',
                                                             'vni': 2001},
                                                   'name': 'Leaf1-Leaf2-EPLAN(M2M)-1'}}}
