expected_output = {'network-instance': {'ECMP-Leaf1-Leaf2-Leaf3-L3VPN-01': {'bgp': {'afi-safis': ['IPV4_UNICAST'],
                                                                  'as': 65002,
                                                                  'control-word': False,
                                                                  'flow-label': False,
                                                                  'label-allocation-mode': 'INSTANCE_LABEL',
                                                                  'route-distinguisher': '1.0.0.0:50002',
                                                                  'route-targets': [{'route-target': '123:123',
                                                                                     'route-target-type': 'both'}],
                                                                  'router-id': '1.0.0.0',
                                                                  'total-paths': 3,
                                                                  'total-prefixes': 3,
                                                                  'tunnel-type': 'MPLS',
                                                                  'vni-evi': 0},
                                                          'interfaces': {'swp5.5551': {'interface': 'swp5',
                                                                                       'subinterface': 5551}},
                                                          'l3vrf': {'table-id': 1073741826,
                                                                    'vrf-interface': 'vrf10001'},
                                                          'name': 'ECMP-Leaf1-Leaf2-Leaf3-L3VPN-01',
                                                          'rib-options': {'ipv4': {'max-prefix-limit': 1000,
                                                                                   'threshold': 90},
                                                                          'ipv6': {'max-prefix-limit': 100,
                                                                                   'threshold': 90}},
                                                          'table-connections': [{'address-family': 'IPV6',
                                                                                 'dst-protocol': 'BGP',
                                                                                 'src-dst-instances': [{'dst-instance': 'ECMP-Leaf1-Leaf2-Leaf3-L3VPN-01',
                                                                                                        'src-instance': 'directly_connected'}],
                                                                                 'src-protocol': 'DIRECTLY_CONNECTED'},
                                                                                {'address-family': 'IPV4',
                                                                                 'dst-protocol': 'BGP',
                                                                                 'src-dst-instances': [{'dst-instance': 'ECMP-Leaf1-Leaf2-Leaf3-L3VPN-01',
                                                                                                        'src-instance': 'directly_connected'}],
                                                                                 'src-protocol': 'DIRECTLY_CONNECTED'},
                                                                                {'address-family': 'IPV6',
                                                                                 'dst-protocol': 'BGP',
                                                                                 'src-protocol': 'STATIC'},
                                                                                {'address-family': 'IPV4',
                                                                                 'dst-protocol': 'BGP',
                                                                                 'src-protocol': 'STATIC'}]}}}
