expected_output = {'neighbors': {'3.0.0.0': {'neighbor-address': '3.0.0.0',
                           'enabled': False,
                           'peer-as': 65000,
                           'local-as': 65000,
                           'peer-type': 'INTERNAL',
                           'session-state': 'SHUTDOWN',
                           'established-transitions': '0',
                           'shutdown': True,
                           'shutdown-reason': 'admin',
                           'messages-sent': {'UPDATE': '0',
                                             'NOTIFICATION': '0',
                                             'KEEPALIVE': '0',
                                             'total': '0'},
                           'messages-received': {'UPDATE': '0',
                                                 'NOTIFICATION': '0',
                                                 'KEEPALIVE': '0',
                                                 'total': '0'},
                           'transport': {'local-address': '0.0.0.0',
                                         'local-port': 0,
                                         'remote-address': '3.0.0.0',
                                         'remote-port': 0},
                           'afi-safis': ['IPV4_UNICAST', 'L2VPN_EVPN']},
               '4.0.0.0': {'neighbor-address': '4.0.0.0',
                           'peer-group': 'IBGP-PEERS',
                           'enabled': True,
                           'peer-as': 65000,
                           'local-as': 65000,
                           'peer-type': 'INTERNAL',
                           'description': 'spine-4',
                           'session-state': 'ESTABLISHED',
                           'established-transitions': '1',
                           'remote-router-id': '4.0.0.0',
                           'last-established': '1710000000',
                           'session-elapsed-time': '2d 05:30:12',
                           'messages-sent': {'UPDATE': '120',
                                             'NOTIFICATION': '0',
                                             'KEEPALIVE': '5400',
                                             'total': '5520'},
                           'messages-received': {'UPDATE': '85',
                                                 'NOTIFICATION': '0',
                                                 'KEEPALIVE': '5400',
                                                 'total': '5485'},
                           'transport': {'local-address': '1.0.0.0',
                                         'local-port': 179,
                                         'remote-address': '4.0.0.0',
                                         'remote-port': 43250}},
               '181.1.1.2': {'neighbor-address': '181.1.1.2',
                             'peer-group': 'EBGP-PEERS',
                             'enabled': True,
                             'peer-as': 10000,
                             'local-as': 65000,
                             'peer-type': 'EXTERNAL',
                             'session-state': 'ESTABLISHED',
                             'established-transitions': '3',
                             'remote-router-id': '181.1.1.2',
                             'last-established': '1710001000',
                             'session-elapsed-time': '1d 12:00:05',
                             'last-reset-reason': 'Hold timer expired',
                             'messages-sent': {'UPDATE': '45',
                                               'NOTIFICATION': '2',
                                               'KEEPALIVE': '2700',
                                               'total': '2747'},
                             'messages-received': {'UPDATE': '30',
                                                   'NOTIFICATION': '1',
                                                   'KEEPALIVE': '2700',
                                                   'total': '2731'},
                             'transport': {'local-address': '181.1.1.1',
                                           'local-port': 35000,
                                           'remote-address': '181.1.1.2',
                                           'remote-port': 179}}}}
