expected_output = {'network-instance': {'default': {'isis': {'default': {'config': {'global': {'net': ['49.0001.1111.1111.1111.00'],
                                                                             'level-capability': 'LEVEL_2',
                                                                             'max-ecmp-paths': 16,
                                                                             'graceful-restart-enabled': True,
                                                                             'lsp-mtu-size': 8000,
                                                                             'segment-routing-enabled': False,
                                                                             'srv6': {'enabled': True,
                                                                                      'locators': ['base_slice0',
                                                                                                   'base_slice131',
                                                                                                   'base_slice132']},
                                                                             'traffic-engineering': {'ipv6-router-id': '2400:2020:0:905::1'},
                                                                             'micro-loop-avoidance': {'srv6-enabled': True,
                                                                                                      'rib-update-delay': 60000},
                                                                             'flexible-algorithms': {'131': {'id': 131,
                                                                                                             'advertise-definition-enabled': True,
                                                                                                             'metric-type': 'arcos-openconfig-isis-augments:LINK_DELAY'},
                                                                                                     '132': {'id': 132,
                                                                                                             'advertise-definition-enabled': True,
                                                                                                             'metric-type': 'arcos-openconfig-isis-augments:IGP_METRIC'}},
                                                                             'dynamic-delay-measurement': {'probe-interval': 20,
                                                                                                           'advertisement-interval': 60},
                                                                             'lsp-bit': {'overload-bit': {'set-bit-on-boot': True,
                                                                                                          'advertise-high-metric': True,
                                                                                                          'reset-triggers': [{'reset-trigger': 'arcos-isis-types:WAIT_DELAY',
                                                                                                                              'delay': 500}]},
                                                                                         'attached-bit': {'ignore-bit': True,
                                                                                                          'suppress-bit': True}}},
                                                                  'levels': {'2': {'level-number': 2,
                                                                                   'enabled': True,
                                                                                   'authentication': {'lsp-authentication': False,
                                                                                                      'auth-password': '$8$P116vHF0+EDlx1jNJecNY+oosPeqDFOS82XLteuqzMI=',
                                                                                                      'crypto-algorithm': 'arcos-openconfig-isis-augments:MD5'}}},
                                                                  'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                'safi-name': 'UNICAST',
                                                                                                'enabled': True,
                                                                                                'multi-topology-enabled': True,
                                                                                                'summary-prefixes': {'2400:2020:0:100::/56': {'prefix': '2400:2020:0:100::/56',
                                                                                                                                              'level': 'LEVEL_2',
                                                                                                                                              'algorithm': 0,
                                                                                                                                              'adv-unreachable': True},
                                                                                                                     '2400:2020:0:900::/56': {'prefix': '2400:2020:0:900::/56',
                                                                                                                                              'level': 'LEVEL_1',
                                                                                                                                              'algorithm': 0,
                                                                                                                                              'tag': 100}},
                                                                                                'prefix-unreachable': {'adv-lifetime': 65535,
                                                                                                                       'adv-metric': 4294967294,
                                                                                                                       'adv-maximum': 65535,
                                                                                                                       'rx-process': True}},
                                                                               'IPV4-UNICAST': {'afi-name': 'IPV4',
                                                                                                'safi-name': 'UNICAST',
                                                                                                'enabled': True}},
                                                                  'interfaces': {'swp1': {'interface-id': 'swp1',
                                                                                          'enabled': True,
                                                                                          'network-type': 'POINT_TO_POINT',
                                                                                          'authentication': {'hello-authentication': True,
                                                                                                             'auth-password': '$8$ob8IZ1eMMUhk0tZVHJ933X4+F7xnbfJdC4jAQch+oBs=',
                                                                                                             'crypto-algorithm': 'arcos-openconfig-isis-augments:MD5'},
                                                                                          'timers': {'hello-interval': 15,
                                                                                                     'hello-multiplier': 5},
                                                                                          'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                                        'safi-name': 'UNICAST',
                                                                                                                        'enabled': True,
                                                                                                                        'fast-reroute': {'ti-lfa-srv6-enabled': True}},
                                                                                                       'IPV4-UNICAST': {'afi-name': 'IPV4',
                                                                                                                        'safi-name': 'UNICAST',
                                                                                                                        'enabled': True}},
                                                                                          'levels': {'1': {'level-number': 1,
                                                                                                           'metric': 100},
                                                                                                     '2': {'level-number': 2,
                                                                                                           'enabled': True,
                                                                                                           'metric': 200,
                                                                                                           'flexible-algorithm': {'delay-metric': 1000000,
                                                                                                                                  'te-metric': 1000000}}},
                                                                                          'interface-ref': {'interface': 'swp1',
                                                                                                            'subinterface': 0}},
                                                                                 'swp3': {'interface-id': 'swp3',
                                                                                          'enabled': True,
                                                                                          'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                                        'safi-name': 'UNICAST',
                                                                                                                        'enabled': True,
                                                                                                                        'fast-reroute': {'ti-lfa-srv6-enabled': True}}},
                                                                                          'levels': {'2': {'level-number': 2,
                                                                                                           'enabled': True}},
                                                                                          'interface-ref': {'interface': 'swp3',
                                                                                                            'subinterface': 0}},
                                                                                 'swp4': {'interface-id': 'swp4',
                                                                                          'enabled': True,
                                                                                          'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                                        'safi-name': 'UNICAST',
                                                                                                                        'enabled': True,
                                                                                                                        'fast-reroute': {'ti-lfa-srv6-enabled': True}}},
                                                                                          'levels': {'2': {'level-number': 2,
                                                                                                           'enabled': True}},
                                                                                          'interface-ref': {'interface': 'swp4',
                                                                                                            'subinterface': 0}},
                                                                                 'loopback0': {'interface-id': 'loopback0',
                                                                                               'enabled': True,
                                                                                               'tag': [1],
                                                                                               'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                                             'safi-name': 'UNICAST',
                                                                                                                             'enabled': True},
                                                                                                            'IPV4-UNICAST': {'afi-name': 'IPV4',
                                                                                                                             'safi-name': 'UNICAST',
                                                                                                                             'enabled': True}},
                                                                                               'levels': {'2': {'level-number': 2,
                                                                                                                'enabled': True}},
                                                                                               'interface-ref': {'interface': 'loopback0',
                                                                                                                 'subinterface': 0}},
                                                                                 'loopback1': {'interface-id': 'loopback1',
                                                                                               'enabled': True,
                                                                                               'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                                             'safi-name': 'UNICAST',
                                                                                                                             'enabled': True}},
                                                                                               'levels': {'2': {'level-number': 2,
                                                                                                                'enabled': True}},
                                                                                               'interface-ref': {'interface': 'loopback1',
                                                                                                                 'subinterface': 0}}}}}}}}}
