expected_output = {'network-instance': {'default': {'isis': {'default': {'config': {'global': {'net': ['49.0001.1111.1111.1111.00'],
                                                                             'level-capability': 'LEVEL_2',
                                                                             'segment-routing-enabled': True},
                                                                  'interfaces': {'swp1': {'interface-id': 'swp1',
                                                                                          'enabled': True,
                                                                                          'network-type': 'POINT_TO_POINT',
                                                                                          'afi-safi': {'IPV4-UNICAST': {'afi-name': 'IPV4',
                                                                                                                        'safi-name': 'UNICAST',
                                                                                                                        'enabled': True,
                                                                                                                        'fast-reroute': {'ti-lfa-sr-mpls-enabled': True},
                                                                                                                        'adjacency-sids': [{'neighbor': 'POINT_TO_POINT',
                                                                                                                                            'sid-type': 'INDEX',
                                                                                                                                            'value': 12}]}},
                                                                                          'interface-ref': {'interface': 'swp1',
                                                                                                            'subinterface': 0}},
                                                                                 'loopback0': {'interface-id': 'loopback0',
                                                                                               'enabled': True,
                                                                                               'afi-safi': {'IPV4-UNICAST': {'afi-name': 'IPV4',
                                                                                                                             'safi-name': 'UNICAST',
                                                                                                                             'enabled': True,
                                                                                                                             'prefix-sids': [{'algorithm': 'SPF',
                                                                                                                                              'sid-type': 'INDEX',
                                                                                                                                              'value': 111,
                                                                                                                                              'label-option': 'EXPLICIT_NULL'}]}},
                                                                                               'interface-ref': {'interface': 'loopback0',
                                                                                                                 'subinterface': 0}}}}}}}}}
