expected_output = {'network-instance': {'default': {'isis': {'default': {'config': {'global': {'net': ['49.0000.0000.0000.0005.00',
                                                                                     '49.2000.0000.0000.0005.00'],
                                                                             'level-capability': 'LEVEL_1_2',
                                                                             'max-ecmp-paths': 16,
                                                                             'graceful-restart-enabled': True,
                                                                             'lsp-mtu-size': 8000,
                                                                             'segment-routing-enabled': False,
                                                                             'srv6': {'enabled': True,
                                                                                      'locators': ['base_slice0']},
                                                                             'traffic-engineering': {'ipv6-router-id': '2400:2020:0:905::1'},
                                                                             'micro-loop-avoidance': {'srv6-enabled': True,
                                                                                                      'rib-update-delay': 60000},
                                                                             'dynamic-delay-measurement': {'probe-interval': 20,
                                                                                                           'advertisement-interval': 60},
                                                                             'lsp-bit': {'overload-bit': {'set-bit-on-boot': True,
                                                                                                          'advertise-high-metric': True,
                                                                                                          'reset-triggers': [{'reset-trigger': 'arcos-isis-types:WAIT_DELAY',
                                                                                                                              'delay': 500}]},
                                                                                         'attached-bit': {'ignore-bit': True,
                                                                                                          'suppress-bit': True}},
                                                                             'inter-level-policies': {'level1-to-level2': {'import-policy': ['906']},
                                                                                                      'level2-to-level1': {'import-policy': ['v6_L2_to_L1']}}},
                                                                  'levels': {'1': {'level-number': 1,
                                                                                   'enabled': True,
                                                                                   'authentication': {'lsp-authentication': False,
                                                                                                      'auth-password': '$8$5w+InKbha4JfryYqj2JUdHk4cpNiTqxurUj3voQn8RY=',
                                                                                                      'crypto-algorithm': 'arcos-openconfig-isis-augments:MD5'}},
                                                                             '2': {'level-number': 2,
                                                                                   'enabled': True,
                                                                                   'authentication': {'lsp-authentication': False,
                                                                                                      'auth-password': '$8$P116vHF0+EDlx1jNJecNY+oosPeqDFOS82XLteuqzMI=',
                                                                                                      'crypto-algorithm': 'arcos-openconfig-isis-augments:MD5'}}},
                                                                  'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                'safi-name': 'UNICAST',
                                                                                                'enabled': True,
                                                                                                'multi-topology-enabled': True,
                                                                                                'summary-prefixes': {'2400:2020:0:100::/56': {'prefix': '2400:2020:0:100::/56',
                                                                                                                                              'level': 'LEVEL_2',
                                                                                                                                              'algorithm': 0,
                                                                                                                                              'adv-unreachable': True},
                                                                                                                     '2400:2020:0:900::/56': {'prefix': '2400:2020:0:900::/56',
                                                                                                                                              'level': 'LEVEL_1',
                                                                                                                                              'algorithm': 0,
                                                                                                                                              'tag': 100},
                                                                                                                     '2400:2020:31:100::/56': {'prefix': '2400:2020:31:100::/56',
                                                                                                                                               'level': 'LEVEL_2',
                                                                                                                                               'algorithm': 131,
                                                                                                                                               'adv-unreachable': True},
                                                                                                                     '2400:2020:31:900::/56': {'prefix': '2400:2020:31:900::/56',
                                                                                                                                               'level': 'LEVEL_1',
                                                                                                                                               'algorithm': 131,
                                                                                                                                               'tag': 100},
                                                                                                                     '2400:2020:32:100::/56': {'prefix': '2400:2020:32:100::/56',
                                                                                                                                               'level': 'LEVEL_2',
                                                                                                                                               'algorithm': 132,
                                                                                                                                               'adv-unreachable': True},
                                                                                                                     '2400:2020:32:900::/56': {'prefix': '2400:2020:32:900::/56',
                                                                                                                                               'level': 'LEVEL_1',
                                                                                                                                               'algorithm': 132,
                                                                                                                                               'tag': 100},
                                                                                                                     '2400:2020:33:100::/56': {'prefix': '2400:2020:33:100::/56',
                                                                                                                                               'level': 'LEVEL_2',
                                                                                                                                               'algorithm': 133,
                                                                                                                                               'adv-unreachable': True},
                                                                                                                     '2400:2020:33:900::/56': {'prefix': '2400:2020:33:900::/56',
                                                                                                                                               'level': 'LEVEL_1',
                                                                                                                                               'algorithm': 133,
                                                                                                                                               'tag': 100},
                                                                                                                     '2400:2020:34:100::/56': {'prefix': '2400:2020:34:100::/56',
                                                                                                                                               'level': 'LEVEL_2',
                                                                                                                                               'algorithm': 134,
                                                                                                                                               'adv-unreachable': True},
                                                                                                                     '2400:2020:34:900::/56': {'prefix': '2400:2020:34:900::/56',
                                                                                                                                               'level': 'LEVEL_1',
                                                                                                                                               'algorithm': 134,
                                                                                                                                               'tag': 100},
                                                                                                                     '2400:2020:35:100::/56': {'prefix': '2400:2020:35:100::/56',
                                                                                                                                               'level': 'LEVEL_2',
                                                                                                                                               'algorithm': 135,
                                                                                                                                               'adv-unreachable': True},
                                                                                                                     '2400:2020:35:900::/56': {'prefix': '2400:2020:35:900::/56',
                                                                                                                                               'level': 'LEVEL_1',
                                                                                                                                               'algorithm': 135,
                                                                                                                                               'tag': 100},
                                                                                                                     '2400:2020:36:100::/56': {'prefix': '2400:2020:36:100::/56',
                                                                                                                                               'level': 'LEVEL_2',
                                                                                                                                               'algorithm': 136,
                                                                                                                                               'adv-unreachable': True},
                                                                                                                     '2400:2020:36:900::/56': {'prefix': '2400:2020:36:900::/56',
                                                                                                                                               'level': 'LEVEL_1',
                                                                                                                                               'algorithm': 136,
                                                                                                                                               'tag': 100},
                                                                                                                     '9000:10:10:1001::/64': {'prefix': '9000:10:10:1001::/64',
                                                                                                                                              'level': 'LEVEL_2',
                                                                                                                                              'tag': 999},
                                                                                                                     '9000:20:20:4200::/56': {'prefix': '9000:20:20:4200::/56',
                                                                                                                                              'level': 'LEVEL_2',
                                                                                                                                              'tag': 5901},
                                                                                                                     '9000:30:30:2000::/51': {'prefix': '9000:30:30:2000::/51',
                                                                                                                                              'level': 'LEVEL_2',
                                                                                                                                              'tag': 9999},
                                                                                                                     'fccc:0:100::/40': {'prefix': 'fccc:0:100::/40',
                                                                                                                                         'level': 'LEVEL_2',
                                                                                                                                         'algorithm': 0,
                                                                                                                                         'adv-unreachable': True},
                                                                                                                     'fccc:0:900::/40': {'prefix': 'fccc:0:900::/40',
                                                                                                                                         'level': 'LEVEL_1',
                                                                                                                                         'algorithm': 0,
                                                                                                                                         'tag': 100},
                                                                                                                     'fccc:31:100::/40': {'prefix': 'fccc:31:100::/40',
                                                                                                                                          'level': 'LEVEL_2',
                                                                                                                                          'algorithm': 131,
                                                                                                                                          'adv-unreachable': True},
                                                                                                                     'fccc:31:900::/40': {'prefix': 'fccc:31:900::/40',
                                                                                                                                          'level': 'LEVEL_1',
                                                                                                                                          'algorithm': 131,
                                                                                                                                          'tag': 100},
                                                                                                                     'fccc:32:100::/40': {'prefix': 'fccc:32:100::/40',
                                                                                                                                          'level': 'LEVEL_2',
                                                                                                                                          'algorithm': 132,
                                                                                                                                          'adv-unreachable': True},
                                                                                                                     'fccc:32:900::/40': {'prefix': 'fccc:32:900::/40',
                                                                                                                                          'level': 'LEVEL_1',
                                                                                                                                          'algorithm': 132,
                                                                                                                                          'tag': 100},
                                                                                                                     'fccc:33:100::/40': {'prefix': 'fccc:33:100::/40',
                                                                                                                                          'level': 'LEVEL_2',
                                                                                                                                          'algorithm': 133,
                                                                                                                                          'adv-unreachable': True},
                                                                                                                     'fccc:33:900::/40': {'prefix': 'fccc:33:900::/40',
                                                                                                                                          'level': 'LEVEL_1',
                                                                                                                                          'algorithm': 133,
                                                                                                                                          'tag': 100},
                                                                                                                     'fccc:34:100::/40': {'prefix': 'fccc:34:100::/40',
                                                                                                                                          'level': 'LEVEL_2',
                                                                                                                                          'algorithm': 134,
                                                                                                                                          'adv-unreachable': True},
                                                                                                                     'fccc:34:900::/40': {'prefix': 'fccc:34:900::/40',
                                                                                                                                          'level': 'LEVEL_1',
                                                                                                                                          'algorithm': 134,
                                                                                                                                          'tag': 100},
                                                                                                                     'fccc:35:100::/40': {'prefix': 'fccc:35:100::/40',
                                                                                                                                          'level': 'LEVEL_2',
                                                                                                                                          'algorithm': 135,
                                                                                                                                          'adv-unreachable': True},
                                                                                                                     'fccc:35:900::/40': {'prefix': 'fccc:35:900::/40',
                                                                                                                                          'level': 'LEVEL_1',
                                                                                                                                          'algorithm': 135,
                                                                                                                                          'tag': 100},
                                                                                                                     'fccc:36:100::/40': {'prefix': 'fccc:36:100::/40',
                                                                                                                                          'level': 'LEVEL_2',
                                                                                                                                          'algorithm': 136,
                                                                                                                                          'adv-unreachable': True},
                                                                                                                     'fccc:36:900::/40': {'prefix': 'fccc:36:900::/40',
                                                                                                                                          'level': 'LEVEL_1',
                                                                                                                                          'algorithm': 136,
                                                                                                                                          'tag': 100}},
                                                                                                'prefix-unreachable': {'adv-lifetime': 65535,
                                                                                                                       'adv-metric': 4294967294,
                                                                                                                       'adv-maximum': 65535,
                                                                                                                       'rx-process': True}}},
                                                                  'interfaces': {'swp1': {'interface-id': 'swp1',
                                                                                          'enabled': True,
                                                                                          'network-type': 'POINT_TO_POINT',
                                                                                          'authentication': {'hello-authentication': True,
                                                                                                             'auth-password': '$8$1tYPNO0VHzGA5P6ok/aZumtJsC4aHoeJhdJs8EJOGSw=',
                                                                                                             'crypto-algorithm': 'arcos-openconfig-isis-augments:MD5'},
                                                                                          'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                                        'safi-name': 'UNICAST',
                                                                                                                        'enabled': True,
                                                                                                                        'fast-reroute': {'ti-lfa-srv6-enabled': True}}},
                                                                                          'levels': {'2': {'level-number': 2,
                                                                                                           'enabled': True,
                                                                                                           'metric': 1000000,
                                                                                                           'flexible-algorithm': {'delay-metric': 1000000,
                                                                                                                                  'te-metric': 1000000}}},
                                                                                          'interface-ref': {'interface': 'swp1',
                                                                                                            'subinterface': 0}},
                                                                                 'swp2': {'interface-id': 'swp2',
                                                                                          'enabled': True,
                                                                                          'network-type': 'POINT_TO_POINT',
                                                                                          'authentication': {'hello-authentication': True,
                                                                                                             'auth-password': '$8$Bryy2NiDdTQxLaQ77DtgEMVa10vHxUG8MJlxPOO8M0E=',
                                                                                                             'crypto-algorithm': 'arcos-openconfig-isis-augments:MD5'},
                                                                                          'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                                        'safi-name': 'UNICAST',
                                                                                                                        'enabled': True,
                                                                                                                        'fast-reroute': {'ti-lfa-srv6-enabled': True}}},
                                                                                          'levels': {'2': {'level-number': 2,
                                                                                                           'enabled': True,
                                                                                                           'metric': 11000,
                                                                                                           'flexible-algorithm': {'delay-metric': 11000,
                                                                                                                                  'te-metric': 11000}}},
                                                                                          'interface-ref': {'interface': 'swp2',
                                                                                                            'subinterface': 0}},
                                                                                 'swp3': {'interface-id': 'swp3',
                                                                                          'enabled': True,
                                                                                          'network-type': 'POINT_TO_POINT',
                                                                                          'authentication': {'hello-authentication': True,
                                                                                                             'auth-password': '$8$BY4jWqBKW5IsP84PlWnZpCiFOH6TNlvtA53f0aq7Fxs=',
                                                                                                             'crypto-algorithm': 'arcos-openconfig-isis-augments:MD5'},
                                                                                          'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                                        'safi-name': 'UNICAST',
                                                                                                                        'enabled': True,
                                                                                                                        'fast-reroute': {'ti-lfa-srv6-enabled': True}}},
                                                                                          'levels': {'1': {'level-number': 1,
                                                                                                           'enabled': True,
                                                                                                           'metric': 100,
                                                                                                           'flexible-algorithm': {'delay-metric': 100,
                                                                                                                                  'te-metric': 100}}},
                                                                                          'interface-ref': {'interface': 'swp3',
                                                                                                            'subinterface': 0}},
                                                                                 'loopback0': {'interface-id': 'loopback0',
                                                                                               'enabled': True,
                                                                                               'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                                             'safi-name': 'UNICAST',
                                                                                                                             'enabled': True}},
                                                                                               'levels': {'1': {'level-number': 1,
                                                                                                                'enabled': True},
                                                                                                          '2': {'level-number': 2,
                                                                                                                'enabled': True}},
                                                                                               'interface-ref': {'interface': 'loopback0',
                                                                                                                 'subinterface': 0}}}}}}}}}
