expected_output = {'network-instance': {'default': {'isis': {'default': {'config': {'global': {'auto-cost-reference-bandwidth': 12345,
                                                                             'mpls-igp-ldp-sync-enabled': True,
                                                                             'hello-authentication': {'enabled': True,
                                                                                                      'keychain': 'abc',
                                                                                                      'auth-type': 'openconfig-keychain-types:KEYCHAIN'}},
                                                                  'levels': {'1': {'level-number': 1,
                                                                                   'authentication': {'lsp-authentication': True,
                                                                                                      'csnp-authentication': True,
                                                                                                      'psnp-authentication': True,
                                                                                                      'auth-type': 'openconfig-keychain-types:KEYCHAIN',
                                                                                                      'keychain': 'abc'},
                                                                                   'traffic-engineering-enabled': True},
                                                                             '2': {'level-number': 2,
                                                                                   'enabled': True,
                                                                                   'authentication': {'lsp-authentication': True,
                                                                                                      'csnp-authentication': True,
                                                                                                      'psnp-authentication': True,
                                                                                                      'auth-type': 'openconfig-keychain-types:KEYCHAIN',
                                                                                                      'keychain': 'abc'},
                                                                                   'traffic-engineering-enabled': True}},
                                                                  'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                'safi-name': 'UNICAST',
                                                                                                'enabled': True,
                                                                                                'default-information': {'enabled': True,
                                                                                                                        'export-policy': ['pass']}}},
                                                                  'interfaces': {'swp1': {'interface-id': 'swp1',
                                                                                          'enabled': True,
                                                                                          'network-type': 'POINT_TO_POINT',
                                                                                          'authentication': {'keychain': 'abc',
                                                                                                             'auth-type': 'openconfig-keychain-types:KEYCHAIN'},
                                                                                          'mpls-igp-ldp-sync-enabled': True,
                                                                                          'afi-safi': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                                                        'safi-name': 'UNICAST',
                                                                                                                        'enabled': True,
                                                                                                                        'fast-reroute': {'ip-enabled': True}}},
                                                                                          'levels': {'2': {'level-number': 2,
                                                                                                           'enabled': True,
                                                                                                           'flexible-algorithm': {'delay-metric': 'arcos-openconfig-isis-augments:DYNAMIC'}}},
                                                                                          'interface-ref': {'interface': 'swp1',
                                                                                                            'subinterface': 0}}}}}}}}}
