expected_output = {'afi-safis': {'IPV4_UNICAST': {'enabled': True,
                                'total-paths': 3000006,
                                'total-prefixes': 3000004,
                                'paths-received': 3000006,
                                'paths-sent': 0,
                                'total-paths-received': 6000012,
                                'total-paths-sent': 0,
                                'total-paths-withdrawn': 0,
                                'rib-install-prefixes': 3000004,
                                'total-next-hops': 2},
               'L2VPN_EVPN': {'enabled': True,
                              'total-paths': 301,
                              'total-prefixes': 267,
                              'paths-received': 301,
                              'paths-sent': 200,
                              'total-paths-received': 602,
                              'total-paths-sent': 400,
                              'total-paths-withdrawn': 0,
                              'rib-install-prefixes': 267,
                              'total-next-hops': 3}}}
