expected_output = {'network_instance': {'default': {'local_sids': {'fcbb:bb00:11:1::/64': {'behavior': 'END_PSP_USD',
                                                                         'client_name': 'sidmgr',
                                                                         'locator_name': 'LOC_R1_ALG129'},
                                                 'fcbb:bb00:11:8012::/64': {'behavior': 'END_X_PSP_USD',
                                                                            'client_name': 'isis-default@defaul',
                                                                            'locator_name': 'LOC_R1_ALG129',
                                                                            'sid_paths': [{'interface': 'swp1',
                                                                                           'next_hop_address': 'fe80::b436:c5ff:fe66:85ed'}]},
                                                 'fcbb:bb00:11:8013::/64': {'behavior': 'END_X_PSP_USD',
                                                                            'client_name': 'isis-default@defaul',
                                                                            'locator_name': 'LOC_R1_ALG129',
                                                                            'sid_paths': [{'interface': 'swp2',
                                                                                           'next_hop_address': 'fe80::84e7:62ff:fe65:4498'}]},
                                                 'fcbb:bb00:11:8014::/64': {'behavior': 'END_X_PSP_USD',
                                                                            'client_name': 'isis-default@defaul',
                                                                            'locator_name': 'LOC_R1_ALG129',
                                                                            'sid_paths': [{'interface': 'swp3',
                                                                                           'next_hop_address': 'fe80::7074:61ff:fee2:5407'}]},
                                                 'fcbb:bb00:11:8015::/64': {'behavior': 'END_X_PSP_USD',
                                                                            'client_name': 'isis-default@defaul',
                                                                            'locator_name': 'LOC_R1_ALG129',
                                                                            'sid_paths': [{'interface': 'swp4',
                                                                                           'next_hop_address': 'fe80::75:b6ff:fe8d:ec0e'}]},
                                                 'fcbb:bb00:1:1::/64': {'behavior': 'END_PSP_USD',
                                                                        'client_name': 'sidmgr',
                                                                        'locator_name': 'LOC_R1_ALG128'},
                                                 'fcbb:bb00:1:8012::/64': {'behavior': 'END_X_PSP_USD',
                                                                           'client_name': 'isis-default@defaul',
                                                                           'locator_name': 'LOC_R1_ALG128',
                                                                           'sid_paths': [{'interface': 'swp1',
                                                                                          'next_hop_address': 'fe80::b436:c5ff:fe66:85ed'}]},
                                                 'fcbb:bb00:1:8013::/64': {'behavior': 'END_X_PSP_USD',
                                                                           'client_name': 'isis-default@defaul',
                                                                           'locator_name': 'LOC_R1_ALG128',
                                                                           'sid_paths': [{'interface': 'swp2',
                                                                                          'next_hop_address': 'fe80::84e7:62ff:fe65:4498'}]},
                                                 'fcbb:bb00:1:8014::/64': {'behavior': 'END_X_PSP_USD',
                                                                           'client_name': 'isis-default@defaul',
                                                                           'locator_name': 'LOC_R1_ALG128',
                                                                           'sid_paths': [{'interface': 'swp3',
                                                                                          'next_hop_address': 'fe80::7074:61ff:fee2:5407'}]},
                                                 'fcbb:bb00:1:8015::/64': {'behavior': 'END_X_PSP_USD',
                                                                           'client_name': 'isis-default@defaul',
                                                                           'locator_name': 'LOC_R1_ALG128',
                                                                           'sid_paths': [{'interface': 'swp4',
                                                                                          'next_hop_address': 'fe80::75:b6ff:fe8d:ec0e'}]},
                                                 'fcbb:bb00:21:1::/64': {'behavior': 'END_PSP_USD',
                                                                         'client_name': 'sidmgr',
                                                                         'locator_name': 'LOC_R1_ALG130'},
                                                 'fcbb:bb00:21:8015::/64': {'behavior': 'END_X_PSP_USD',
                                                                            'client_name': 'isis-default@defaul',
                                                                            'locator_name': 'LOC_R1_ALG130',
                                                                            'sid_paths': [{'interface': 'swp1',
                                                                                           'next_hop_address': 'fe80::b436:c5ff:fe66:85ed'}]},
                                                 'fcbb:bb00:21:8016::/64': {'behavior': 'END_X_PSP_USD',
                                                                            'client_name': 'isis-default@defaul',
                                                                            'locator_name': 'LOC_R1_ALG130',
                                                                            'sid_paths': [{'interface': 'swp2',
                                                                                           'next_hop_address': 'fe80::84e7:62ff:fe65:4498'}]},
                                                 'fcbb:bb00:21:8017::/64': {'behavior': 'END_X_PSP_USD',
                                                                            'client_name': 'isis-default@defaul',
                                                                            'locator_name': 'LOC_R1_ALG130',
                                                                            'sid_paths': [{'interface': 'swp3',
                                                                                           'next_hop_address': 'fe80::7074:61ff:fee2:5407'}]},
                                                 'fcbb:bb00:21:8018::/64': {'behavior': 'END_X_PSP_USD',
                                                                            'client_name': 'isis-default@defaul',
                                                                            'locator_name': 'LOC_R1_ALG130',
                                                                            'sid_paths': [{'interface': 'swp4',
                                                                                           'next_hop_address': 'fe80::75:b6ff:fe8d:ec0e'}]}}}}}
