expected_output = {'network-instance': {'default': {'isis': {'default': {'mpls': {'igp-ldp-sync-enabled': False,
                                                                'label-db': {'state': {'protocol-identifier': 'ISIS',
                                                                                       'protocol-name': 'default',
                                                                                       'configured-blocks': 2,
                                                                                       'active-blocks': 2,
                                                                                       'active-usages': 2},
                                                                             'statistics': {'label-space': 20000,
                                                                                            'labels': 6,
                                                                                            'allocs': '7',
                                                                                            'frees': '5',
                                                                                            'alloc-errors': '0',
                                                                                            'free-errors': '4'},
                                                                             'usages': {'ISIS_SRGB': {'usage': 'ISIS_SRGB',
                                                                                                      'blocks-count': 1,
                                                                                                      'opaque-flags': '0c',
                                                                                                      'statistics': {'label-space': 10000,
                                                                                                                     'labels': 3,
                                                                                                                     'allocs': '3',
                                                                                                                     'frees': '0',
                                                                                                                     'alloc-errors': '0',
                                                                                                                     'free-errors': '0'},
                                                                                                      'blocks': {'10000': {'lower-bound': 10000,
                                                                                                                           'upper-bound': 19999,
                                                                                                                           'block-name': 'rb1',
                                                                                                                           'opaque-flags': '0d',
                                                                                                                           'statistics': {'label-space': 10000,
                                                                                                                                          'labels': 3,
                                                                                                                                          'allocs': '3',
                                                                                                                                          'frees': '0',
                                                                                                                                          'alloc-errors': '0',
                                                                                                                                          'free-errors': '0'}}},
                                                                                                      'labels': {'10111': {'label': 10111,
                                                                                                                           'block-name': 'rb1',
                                                                                                                           'label-key': {'type': 'KEY_IPV4_PREFIX',
                                                                                                                                         'sub-type': 0,
                                                                                                                                         'table-id': 1,
                                                                                                                                         'ip-prefix': '1.1.1.1/32'}},
                                                                                                                 '10222': {'label': 10222,
                                                                                                                           'block-name': 'rb1',
                                                                                                                           'label-key': {'type': 'KEY_IPV4_PREFIX',
                                                                                                                                         'sub-type': 0,
                                                                                                                                         'table-id': 1,
                                                                                                                                         'ip-prefix': '2.2.2.2/32'}},
                                                                                                                 '10333': {'label': 10333,
                                                                                                                           'block-name': 'rb1',
                                                                                                                           'label-key': {'type': 'KEY_IPV4_PREFIX',
                                                                                                                                         'sub-type': 0,
                                                                                                                                         'table-id': 1,
                                                                                                                                         'ip-prefix': '3.3.3.3/32'}}}},
                                                                                        'ISIS_SRLB': {'usage': 'ISIS_SRLB',
                                                                                                      'blocks-count': 1,
                                                                                                      'opaque-flags': '0c',
                                                                                                      'statistics': {'label-space': 10000,
                                                                                                                     'labels': 3,
                                                                                                                     'allocs': '4',
                                                                                                                     'frees': '5',
                                                                                                                     'alloc-errors': '0',
                                                                                                                     'free-errors': '4'},
                                                                                                      'blocks': {'20000': {'lower-bound': 20000,
                                                                                                                           'upper-bound': 29999,
                                                                                                                           'block-name': 'rb2',
                                                                                                                           'opaque-flags': '0d',
                                                                                                                           'statistics': {'label-space': 10000,
                                                                                                                                          'labels': 3,
                                                                                                                                          'allocs': '4',
                                                                                                                                          'frees': '5',
                                                                                                                                          'alloc-errors': '0',
                                                                                                                                          'free-errors': '4'}}},
                                                                                                      'labels': {'20012': {'label': 20012,
                                                                                                                           'block-name': 'rb2',
                                                                                                                           'label-key': {'type': 'KEY_IPV4_ADJ',
                                                                                                                                         'sub-type': 0,
                                                                                                                                         'table-id': 1,
                                                                                                                                         'nh-address': '10.20.0.20',
                                                                                                                                         'ifindex': '802'}},
                                                                                                                 '20013': {'label': 20013,
                                                                                                                           'block-name': 'rb2',
                                                                                                                           'label-key': {'type': 'KEY_IPV4_ADJ',
                                                                                                                                         'sub-type': 0,
                                                                                                                                         'table-id': 1,
                                                                                                                                         'nh-address': '10.30.0.30',
                                                                                                                                         'ifindex': '808'}},
                                                                                                                 '20122': {'label': 20122,
                                                                                                                           'block-name': 'rb2',
                                                                                                                           'label-key': {'type': 'KEY_IPV4_ADJ',
                                                                                                                                         'sub-type': 0,
                                                                                                                                         'table-id': 1,
                                                                                                                                         'nh-address': '10.20.2.20',
                                                                                                                                         'ifindex': '806'}}}}}}}}}}}}
