expected_output = {'network-instance': {'default': {'address-family': 'IPV4',
                                  'label-entries': {'10001': {'control-word': False,
                                                              'fec': '1.1.1.1/32',
                                                              'flags': '',
                                                              'flow-label': False,
                                                              'label': 10001,
                                                              'label-type': 'DEAGG',
                                                              'last-updated': '2026-03-08T10:25:58.308835-00:00',
                                                              'nhid': '0',
                                                              'protocol': 'ISIS',
                                                              'time-since-creation': '0d 04:32:38',
                                                              'vpn-table-id': 1},
                                                    '10002': {'fec': '2.2.2.2/32',
                                                              'flags': 'ECMP_FEC_OPTIMIZE',
                                                              'label': 10002,
                                                              'label-type': 'NONE',
                                                              'last-updated': '2026-03-08T10:25:58.742669-00:00',
                                                              'nhid': '635',
                                                              'protocol': 'ISIS',
                                                              'time-since-creation': '0d 04:32:37',
                                                              'vpn-table-id': 1},
                                                    '10004': {'fec': '4.4.4.4/32',
                                                              'flags': 'ECMP_FEC_OPTIMIZE',
                                                              'label': 10004,
                                                              'label-type': 'NONE',
                                                              'last-updated': '2026-03-08T10:25:58.742429-00:00',
                                                              'nhid': '641',
                                                              'protocol': 'ISIS',
                                                              'time-since-creation': '0d 04:32:37',
                                                              'vpn-table-id': 1},
                                                    '10005': {'fec': '5.5.5.5/32',
                                                              'flags': 'ECMP_FEC_OPTIMIZE',
                                                              'label': 10005,
                                                              'label-type': 'NONE',
                                                              'last-updated': '2026-03-08T10:25:58.742922-00:00',
                                                              'nhid': '643',
                                                              'protocol': 'ISIS',
                                                              'time-since-creation': '0d 04:32:37',
                                                              'vpn-table-id': 1},
                                                    '20121': {'flags': '',
                                                              'label': 20121,
                                                              'label-type': 'NONE',
                                                              'last-updated': '2026-03-08T10:25:58.310563-00:00',
                                                              'nhid': '635',
                                                              'protocol': 'ISIS',
                                                              'time-since-creation': '0d 04:32:38',
                                                              'vpn-table-id': 1},
                                                    '20141': {'flags': '',
                                                              'label': 20141,
                                                              'label-type': 'NONE',
                                                              'last-updated': '2026-03-08T10:25:58.310693-00:00',
                                                              'nhid': '637',
                                                              'protocol': 'ISIS',
                                                              'time-since-creation': '0d 04:32:38',
                                                              'vpn-table-id': 1},
                                                    '21441': {'flags': '',
                                                              'label': 21441,
                                                              'label-type': 'NONE',
                                                              'last-updated': '2026-03-08T10:25:58.31089-00:00',
                                                              'nhid': '639',
                                                              'protocol': 'ISIS',
                                                              'time-since-creation': '0d 04:32:38',
                                                              'vpn-table-id': 1}}}}}
