expected_output = {'network-instance': {'default': {'bgp': {'default': {'config': {'as': 65002,
                                                                 'router-id': '1.0.0.0',
                                                                 'adj-rib-out-post': True,
                                                                 'label-allocation-mode': 'INSTANCE_LABEL',
                                                                 'drop-upon-invalid-sr-policy': False,
                                                                 'ignore-next-hop-igp-metric': True,
                                                                 'compatibility': {'l2-attr-local': True},
                                                                 'afi-safis': {'IPV6_LABELED_UNICAST': {'null-label': 'EXPLICIT'},
                                                                               'IPV4_UNICAST': {'ibgp-maximum-paths': 8,
                                                                                                'add-paths-calculate': 'MULTIPATHS',
                                                                                                'networks': ['144.144.144.144/32'],
                                                                                                'aggregate-addresses': {'201.0.0.0/8': {'summary-only': True}}},
                                                                               'IPV4_LABELED_UNICAST': {'ibgp-maximum-paths': 8,
                                                                                                        'add-paths-calculate': 'MULTIPATHS'},
                                                                               'L3VPN_IPV6_UNICAST': {'ibgp-maximum-paths': 8,
                                                                                                      'add-paths-calculate': 'MULTIPATHS'},
                                                                               'IPV6_UNICAST': {'ibgp-maximum-paths': 8,
                                                                                                'add-paths-calculate': 'MULTIPATHS',
                                                                                                'aggregate-addresses': {'201::/16': {'summary-only': True}}},
                                                                               'L2VPN_EVPN': {'ibgp-maximum-paths': 8,
                                                                                              'add-paths-calculate': 'MULTIPATHS'},
                                                                               'L3VPN_IPV4_UNICAST': {'ibgp-maximum-paths': 8,
                                                                                                      'add-paths-calculate': 'MULTIPATHS',
                                                                                                      'rtfilter-enabled': True},
                                                                               'RTFILTER': {}}},
                                                      'neighbors': {'3.0.0.0': {'peer-as': 65002,
                                                                                'description': 'Enable '
                                                                                               'only '
                                                                                               'to '
                                                                                               'bypass '
                                                                                               'RR '
                                                                                               '(S1,S2) '
                                                                                               'to '
                                                                                               'test '
                                                                                               'TILFA',
                                                                                'shutdown': True,
                                                                                'transport-local-address': '1.0.0.0',
                                                                                'bfd-enable': False,
                                                                                'afi-safis': {'IPV6_LABELED_UNICAST': {},
                                                                                              'IPV4_UNICAST': {'add-paths-receive': True},
                                                                                              'IPV4_LABELED_UNICAST': {'add-paths-send': 'BACKUP',
                                                                                                                       'add-paths-receive': True},
                                                                                              'L3VPN_IPV6_UNICAST': {},
                                                                                              'L2VPN_EVPN': {'add-paths-send': 'BACKUP',
                                                                                                             'add-paths-receive': True},
                                                                                              'L3VPN_IPV4_UNICAST': {'add-paths-send': 'ALL',
                                                                                                                     'add-paths-receive': True},
                                                                                              'RTFILTER': {}}},
                                                                    '4.0.0.0': {'peer-group': 'RR-Peer-Group'},
                                                                    '5.0.0.0': {'peer-group': 'RR-Peer-Group'},
                                                                    '181.1.1.2': {'peer-as': 10000,
                                                                                  'peer-group': 'access_v4_peer_grp',
                                                                                  'transport-local-address': '181.1.1.1'},
                                                                    '181.1.5.2': {'peer-as': 10001,
                                                                                  'peer-group': 'access_v4_peer_grp',
                                                                                  'transport-local-address': '181.1.5.1'},
                                                                    '181:1:1::2': {'peer-as': 10000,
                                                                                   'peer-group': 'access_v6_peer_grp',
                                                                                   'transport-local-address': '181:1:1::1'},
                                                                    '181:1:5::2': {'peer-as': 10001,
                                                                                   'peer-group': 'access_v6_peer_grp',
                                                                                   'transport-local-address': '181:1:5::1'}},
                                                      'peer-groups': {'RR-Peer-Group': {'peer-as': 65002,
                                                                                        'shutdown': False,
                                                                                        'transport-local-address': '1.0.0.0',
                                                                                        'bfd-enable': True,
                                                                                        'bfd-profile': 'GLOBAL-200m',
                                                                                        'afi-safis': {'IPV6_LABELED_UNICAST': {},
                                                                                                      'IPV4_UNICAST': {'add-paths-receive': True},
                                                                                                      'IPV4_LABELED_UNICAST': {'add-paths-send': 'BACKUP',
                                                                                                                               'add-paths-receive': True},
                                                                                                      'L3VPN_IPV6_UNICAST': {},
                                                                                                      'L2VPN_EVPN': {'add-paths-send': 'BACKUP',
                                                                                                                     'add-paths-receive': True},
                                                                                                      'L3VPN_IPV4_UNICAST': {'add-paths-send': 'ALL',
                                                                                                                             'add-paths-receive': True},
                                                                                                      'RTFILTER': {}}},
                                                                      'access_v4_peer_grp': {'afi-safis': {'IPV4_UNICAST': {'add-paths-receive': True,
                                                                                                                            'import-policy': ['accept_all']},
                                                                                                           'IPV4_LABELED_UNICAST': {'add-paths-send': 'BACKUP',
                                                                                                                                    'add-paths-receive': True}}},
                                                                      'access_v6_peer_grp': {'afi-safis': {'IPV6_UNICAST': {}}}}}}}}}
