expected_output = {'hello-adjacencies': {'1.1.1.1:TARGETED': {'adjacency-type': 'TARGETED',
                                            'holdtime': 45,
                                            'interface': 'swp1',
                                            'label-space-id': 0,
                                            'lsr-id': '1.1.1.1',
                                            'peer-address': '1.1.1.1',
                                            'reset-count': 0,
                                            'source-address': '1.1.1.1',
                                            'transport-address': '1.1.1.1',
                                            'uptime': '0d 00:00:46',
                                            'version': 1},
                       '10.12.1.1:LINK': {'adjacency-type': 'LINK',
                                          'holdtime': 15,
                                          'interface': 'swp1',
                                          'label-space-id': 0,
                                          'lsr-id': '1.1.1.1',
                                          'peer-address': '10.12.1.1',
                                          'reset-count': 0,
                                          'source-address': '10.12.1.1',
                                          'transport-address': '1.1.1.1',
                                          'uptime': '0d 00:00:46',
                                          'version': 1},
                       '10.23.2.3:LINK': {'adjacency-type': 'LINK',
                                          'holdtime': 15,
                                          'interface': 'swp2',
                                          'label-space-id': 0,
                                          'lsr-id': '3.3.3.3',
                                          'peer-address': '10.23.2.3',
                                          'reset-count': 0,
                                          'source-address': '10.23.2.3',
                                          'transport-address': '3.3.3.3',
                                          'uptime': '0d 00:00:28',
                                          'version': 1},
                       '3.3.3.3:TARGETED': {'adjacency-type': 'TARGETED',
                                            'holdtime': 45,
                                            'interface': 'swp2',
                                            'label-space-id': 0,
                                            'lsr-id': '3.3.3.3',
                                            'peer-address': '3.3.3.3',
                                            'reset-count': 0,
                                            'source-address': '3.3.3.3',
                                            'transport-address': '3.3.3.3',
                                            'uptime': '0d 00:00:28',
                                            'version': 1}}}
