expected_output = {'network-instances': {'default': {'srv6': {'locators': {'base_slice0': {'algorithm': 0,
                                                                         'function-length': 16,
                                                                         'locator-node-length': 24,
                                                                         'micro-segment-behavior-unode': False,
                                                                         'name': 'base_slice0',
                                                                         'prefix': '2400:2020:0:1191::/64'},
                                                         'base_slice131': {'algorithm': 131,
                                                                           'function-length': 16,
                                                                           'locator-node-length': 24,
                                                                           'micro-segment-behavior-unode': False,
                                                                           'name': 'base_slice131',
                                                                           'prefix': '2400:2020:31:1191::/64'},
                                                         'base_slice132': {'algorithm': 132,
                                                                           'function-length': 16,
                                                                           'locator-node-length': 24,
                                                                           'micro-segment-behavior-unode': False,
                                                                           'name': 'base_slice132',
                                                                           'prefix': '2400:2020:32:1191::/64'}}}}}}
