expected_output = {'profile': {'GLOBAL': {'desired-minimum-tx-interval': 100,
                        'detection-multiplier': 3,
                        'dscp-value': 48,
                        'enabled': True,
                        'id': 'GLOBAL',
                        'required-minimum-receive': 100,
                        'v4-hw-offload': True,
                        'v6-hw-offload': True},
             'GLOBAL-1000m': {'desired-minimum-tx-interval': 1000,
                              'detection-multiplier': 3,
                              'dscp-value': 48,
                              'enabled': True,
                              'id': 'GLOBAL-1000m',
                              'required-minimum-receive': 1000,
                              'v4-hw-offload': True,
                              'v6-hw-offload': True},
             'GLOBAL-100m': {'desired-minimum-tx-interval': 100,
                             'detection-multiplier': 3,
                             'dscp-value': 48,
                             'enabled': True,
                             'id': 'GLOBAL-100m',
                             'required-minimum-receive': 100,
                             'v4-hw-offload': True,
                             'v6-hw-offload': True},
             'GLOBAL-150m': {'desired-minimum-tx-interval': 150,
                             'detection-multiplier': 3,
                             'dscp-value': 48,
                             'enabled': True,
                             'id': 'GLOBAL-150m',
                             'peers': {'20': {'hw-endpoint-id': 20,
                                              'hw-offload-status': True,
                                              'interface': 'swp19',
                                              'local-address': '191.168.7.1',
                                              'local-desired-minimum-tx-interval': 150,
                                              'local-detection-multiplier': 3,
                                              'local-discriminator': '20',
                                              'local-required-minimum-receive': 150,
                                              'negotiated-rx-interval': 450,
                                              'negotiated-tx-interval': 150,
                                              'network-instance': 'default',
                                              'received-packets': '51091',
                                              'remote-address': '191.168.7.0',
                                              'remote-discriminator': '24',
                                              'remote-minimum-receive-interval': 150,
                                              'remote-session-state': 'UP',
                                              'session-state': 'UP',
                                              'session-type': 'BFD_SESSION_TYPE_UDP_IPV4',
                                              'session-up-time': '0d 02:07:58',
                                              'subscribed-protocols': ['ISIS'],
                                              'transmitted-packets': '51086'},
                                       '24': {'hw-endpoint-id': 24,
                                              'hw-offload-status': True,
                                              'interface': 'bond121',
                                              'local-address': '191.168.8.1',
                                              'local-desired-minimum-tx-interval': 150,
                                              'local-detection-multiplier': 3,
                                              'local-discriminator': '24',
                                              'local-required-minimum-receive': 150,
                                              'negotiated-rx-interval': 450,
                                              'negotiated-tx-interval': 150,
                                              'network-instance': 'default',
                                              'received-packets': '51041',
                                              'remote-address': '191.168.8.0',
                                              'remote-discriminator': '32',
                                              'remote-minimum-receive-interval': 150,
                                              'remote-session-state': 'UP',
                                              'session-state': 'UP',
                                              'session-type': 'BFD_SESSION_TYPE_UDP_IPV4',
                                              'session-up-time': '0d 02:07:51',
                                              'subscribed-protocols': ['ISIS'],
                                              'transmitted-packets': '51038'}},
                             'required-minimum-receive': 150,
                             'v4-hw-offload': True,
                             'v6-hw-offload': True},
             'GLOBAL-200m': {'desired-minimum-tx-interval': 200,
                             'detection-multiplier': 3,
                             'dscp-value': 48,
                             'enabled': True,
                             'id': 'GLOBAL-200m',
                             'peers': {'12': {'hw-endpoint-id': 12,
                                              'hw-offload-status': True,
                                              'local-address': '1.0.0.0',
                                              'local-desired-minimum-tx-interval': 200,
                                              'local-detection-multiplier': 3,
                                              'local-discriminator': '12',
                                              'local-required-minimum-receive': 200,
                                              'negotiated-rx-interval': 600,
                                              'negotiated-tx-interval': 200,
                                              'network-instance': 'default',
                                              'received-packets': '38228',
                                              'remote-address': '5.0.0.0',
                                              'remote-discriminator': '16',
                                              'remote-minimum-receive-interval': 200,
                                              'remote-session-state': 'UP',
                                              'session-state': 'UP',
                                              'session-type': 'BFD_SESSION_TYPE_MULTI_HOP_UDP_IPV4',
                                              'session-up-time': '0d 02:07:40',
                                              'subscribed-protocols': ['BGP'],
                                              'transmitted-packets': '38223'},
                                       '16': {'hw-endpoint-id': 16,
                                              'hw-offload-status': True,
                                              'local-address': '1.0.0.0',
                                              'local-desired-minimum-tx-interval': 200,
                                              'local-detection-multiplier': 3,
                                              'local-discriminator': '16',
                                              'local-required-minimum-receive': 200,
                                              'negotiated-rx-interval': 600,
                                              'negotiated-tx-interval': 200,
                                              'network-instance': 'default',
                                              'received-packets': '38248',
                                              'remote-address': '4.0.0.0',
                                              'remote-discriminator': '16',
                                              'remote-minimum-receive-interval': 200,
                                              'remote-session-state': 'UP',
                                              'session-state': 'UP',
                                              'session-type': 'BFD_SESSION_TYPE_MULTI_HOP_UDP_IPV4',
                                              'session-up-time': '0d 02:07:44',
                                              'subscribed-protocols': ['BGP'],
                                              'transmitted-packets': '38244'}},
                             'required-minimum-receive': 200,
                             'v4-hw-offload': True,
                             'v6-hw-offload': True},
             'GLOBAL-250m': {'desired-minimum-tx-interval': 250,
                             'detection-multiplier': 3,
                             'dscp-value': 48,
                             'enabled': True,
                             'id': 'GLOBAL-250m',
                             'required-minimum-receive': 250,
                             'v4-hw-offload': True,
                             'v6-hw-offload': True},
             'GLOBAL-500m-5x': {'desired-minimum-tx-interval': 500,
                                'detection-multiplier': 5,
                                'dscp-value': 48,
                                'enabled': True,
                                'id': 'GLOBAL-500m-5x',
                                'required-minimum-receive': 500,
                                'v4-hw-offload': True,
                                'v6-hw-offload': True}}}
