expected_output = {'interfaces': {'ma1': {'counters': {'frame-discard': '0',
                                     'frame-error-in': '0',
                                     'frame-error-out': '0',
                                     'frame-in': '22891',
                                     'frame-out': '22890',
                                     'tlv-discard': '0',
                                     'tlv-unknown': '0'},
                        'enabled': True,
                        'name': 'ma1',
                        'neighbors': {'1-swp11': {'age': '7 days, 22:46:05',
                                                  'capabilities': {'MAC_BRIDGE': {'enabled': False,
                                                                                  'name': 'MAC_BRIDGE'},
                                                                   'ROUTER': {'enabled': True,
                                                                              'name': 'ROUTER'}},
                                                  'chassis-id': 'e0:01:a6:dc:d4:03',
                                                  'chassis-id-type': 'MAC_ADDRESS',
                                                  'id': '1-swp11',
                                                  'management-address': '10.50.1.203',
                                                  'management-address-ipv6': 'fe80::84f7:69ff:fedc:fa1c',
                                                  'management-address-ipv6-type': 'IPv6 '
                                                                                  'Address',
                                                  'management-address-type': 'IP '
                                                                             'Address',
                                                  'port-description': 'swp11',
                                                  'port-id': 'swp11',
                                                  'port-id-type': 'INTERFACE_NAME',
                                                  'system-description': 'Arrcus '
                                                                        'Operating '
                                                                        'System '
                                                                        '(ArcOS)',
                                                  'system-name': 'eq-mgmt-sw-rack203'}}},
                'swp14': {'counters': {'frame-discard': '0',
                                       'frame-error-in': '0',
                                       'frame-error-out': '0',
                                       'frame-in': '0',
                                       'frame-out': '0',
                                       'tlv-discard': '0',
                                       'tlv-unknown': '0'},
                          'enabled': True,
                          'name': 'swp14'},
                'swp3': {'counters': {'frame-discard': '0',
                                      'frame-error-in': '0',
                                      'frame-error-out': '0',
                                      'frame-in': '22868',
                                      'frame-out': '22872',
                                      'tlv-discard': '0',
                                      'tlv-unknown': '0'},
                         'enabled': True,
                         'name': 'swp3',
                         'neighbors': {'6-swp3': {'age': '6 days, 16:38:06',
                                                  'capabilities': {'MAC_BRIDGE': {'enabled': False,
                                                                                  'name': 'MAC_BRIDGE'},
                                                                   'ROUTER': {'enabled': True,
                                                                              'name': 'ROUTER'}},
                                                  'chassis-id': '5c:07:58:ab:42:02',
                                                  'chassis-id-type': 'MAC_ADDRESS',
                                                  'id': '6-swp3',
                                                  'management-address': '10.50.203.13',
                                                  'management-address-ipv6': '214:100:100::1',
                                                  'management-address-ipv6-type': 'IPv6 '
                                                                                  'Address',
                                                  'management-address-type': 'IP '
                                                                             'Address',
                                                  'port-description': 'swp3',
                                                  'port-id': 'swp3',
                                                  'port-id-type': 'INTERFACE_NAME',
                                                  'system-description': 'Arrcus '
                                                                        'Operating '
                                                                        'System '
                                                                        '(ArcOS)',
                                                  'system-name': 'Metro2-S2-46Dx-203-13'}}}}}
