expected_output = {'network-instance': {'default': {'isis': {'default': {'fast-reroute': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                         'safi-name': 'UNICAST',
                                                                                         'prefixes': {'2::2/128': {'prefix': '2::2/128',
                                                                                                                   'levels': {'2': {'level-number': 2,
                                                                                                                                    'reroute-type': 'TI_LFA',
                                                                                                                                    'metric': 20,
                                                                                                                                    'nexthop-address': '::',
                                                                                                                                    'nexthop-interface': 'swp4',
                                                                                                                                    'flags': ['arcos-openconfig-isis-augments:PQ_IS_REMOTE'],
                                                                                                                                    'last-updated-time': '2025-11-27T01:40:37.406529+00:00',
                                                                                                                                    'origin-system-id': 'rtr2.00',
                                                                                                                                    'protection-types': ['LINK_PROTECTION'],
                                                                                                                                    'pq-node-system-id': 'rtr3.00'}}},
                                                                                                      '3::3/128': {'prefix': '3::3/128',
                                                                                                                   'levels': {'2': {'level-number': 2,
                                                                                                                                    'reroute-type': 'TI_LFA',
                                                                                                                                    'metric': 20,
                                                                                                                                    'nexthop-address': 'fe80::6c80:efff:feda:2f14',
                                                                                                                                    'nexthop-interface': 'swp1',
                                                                                                                                    'flags': ['arcos-openconfig-isis-augments:PQ_IS_ADJACENT'],
                                                                                                                                    'last-updated-time': '2025-11-27T01:40:37.40641+00:00',
                                                                                                                                    'origin-system-id': 'rtr3.00',
                                                                                                                                    'protection-types': ['LINK_PROTECTION'],
                                                                                                                                    'pq-node-system-id': 'rtr2.00'}}},
                                                                                                      '2400:2020:0:2291::/64': {'prefix': '2400:2020:0:2291::/64',
                                                                                                                                'levels': {'2': {'level-number': 2,
                                                                                                                                                 'reroute-type': 'TI_LFA',
                                                                                                                                                 'metric': 20,
                                                                                                                                                 'nexthop-address': '::',
                                                                                                                                                 'nexthop-interface': 'swp4',
                                                                                                                                                 'flags': ['arcos-openconfig-isis-augments:PQ_IS_REMOTE'],
                                                                                                                                                 'last-updated-time': '2025-11-27T01:40:37.406544+00:00',
                                                                                                                                                 'origin-system-id': 'rtr2.00',
                                                                                                                                                 'protection-types': ['LINK_PROTECTION'],
                                                                                                                                                 'pq-node-system-id': 'rtr3.00'}}},
                                                                                                      '2400:2020:0:3391::/64': {'prefix': '2400:2020:0:3391::/64',
                                                                                                                                'levels': {'2': {'level-number': 2,
                                                                                                                                                 'reroute-type': 'TI_LFA',
                                                                                                                                                 'metric': 20,
                                                                                                                                                 'nexthop-address': 'fe80::6c80:efff:feda:2f14',
                                                                                                                                                 'nexthop-interface': 'swp1',
                                                                                                                                                 'flags': ['arcos-openconfig-isis-augments:PQ_IS_ADJACENT'],
                                                                                                                                                 'last-updated-time': '2025-11-27T01:40:37.406468+00:00',
                                                                                                                                                 'origin-system-id': 'rtr3.00',
                                                                                                                                                 'protection-types': ['LINK_PROTECTION'],
                                                                                                                                                 'pq-node-system-id': 'rtr2.00'}}}}}}}}}}}
