expected_output = {'network-instance': {'default': {'isis': {'default': {'fast-reroute': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                         'safi-name': 'UNICAST',
                                                                                         'prefixes': {'fcbb:bb00:96::/48': {'prefix': 'fcbb:bb00:96::/48',
                                                                                                                            'levels': {'2': {'level-number': 2,
                                                                                                                                             'reroute-type': 'TI_LFA',
                                                                                                                                             'metric': 70,
                                                                                                                                             'nexthop-address': 'fe80::f425:65ff:fea5:f639',
                                                                                                                                             'nexthop-interface': 'swp2',
                                                                                                                                             'flags': ['arcos-openconfig-isis-augments:PQ_IS_REMOTE'],
                                                                                                                                             'last-updated-time': '2026-05-18T13:14:34.633187+00:00',
                                                                                                                                             'origin-system-id': 'rtr6.00',
                                                                                                                                             'protection-types': ['NODE_PROTECTION',
                                                                                                                                                                  'LINK_PROTECTION'],
                                                                                                                                             'pq-node-system-id': 'rtr5.00'}}}}}}}}}}}
