expected_output = {'network-instance': {'default': {'isis': {'default': {'fast-reroute': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                         'safi-name': 'UNICAST',
                                                                                         'prefixes': {'fcbb:bb00:96::/48': {'prefix': 'fcbb:bb00:96::/48',
                                                                                                                            'levels': {'2': {'level-number': 2,
                                                                                                                                             'reroute-type': 'TI_LFA',
                                                                                                                                             'metric': 70,
                                                                                                                                             'nexthop-address': 'fe80::f425:65ff:fea5:f639',
                                                                                                                                             'nexthop-interface': 'swp2',
                                                                                                                                             'flags': ['arcos-openconfig-isis-augments:P_AND_Q_ARE_ADJACENT'],
                                                                                                                                             'last-updated-time': '2026-05-18T09:51:36.269794+00:00',
                                                                                                                                             'origin-system-id': 'rtr6.00',
                                                                                                                                             'protection-types': ['NODE_PROTECTION',
                                                                                                                                                                  'LINK_PROTECTION'],
                                                                                                                                             'p-node-system-id': 'rtr4.00',
                                                                                                                                             'q-node-system-id': 'rtr5.00'}}}}}}}}}}}
