expected_output = {'network-instance': {'default': {'isis': {'default': {'fast-reroute': {'IPV6-UNICAST': {'afi-name': 'IPV6',
                                                                                         'safi-name': 'UNICAST',
                                                                                         'prefixes': {'2001::6/128': {'prefix': '2001::6/128',
                                                                                                                      'levels': {'2': {'level-number': 2,
                                                                                                                                       'reroute-type': 'TI_LFA',
                                                                                                                                       'metric': 540,
                                                                                                                                       'nexthop-address': '0.0.0.0',
                                                                                                                                       'nexthop-interface': '',
                                                                                                                                       'flags': [],
                                                                                                                                       'last-updated-time': '2026-05-15T18:36:50.858489+00:00',
                                                                                                                                       'origin-system-id': 'rtr6.00',
                                                                                                                                       'protection-types': ['NODE_PROTECTION',
                                                                                                                                                            'LINK_PROTECTION'],
                                                                                                                                       'p-node-system-id': 'rtr4.00',
                                                                                                                                       'q-node-system-id': '0000.0000.0000.00'}}}}}}}}}}}
