expected_output = {'areas': {'0.0.0.0': {'interfaces': {'swp1': {'exchange-neighbor-count': 0,
                                               'full-neighbor-count': 1,
                                               'id': 'swp1',
                                               'ignore-mtu': False,
                                               'instance-id': 0,
                                               'interface-id': 11,
                                               'interface-state': 'INTERFACE_BACKUP',
                                               'interface-up': True,
                                               'loading-neighbor-count': 0,
                                               'local-ip-address': 'fe80::1016:9bff:fe15:5899',
                                               'metric': 320,
                                               'mtu': 8974,
                                               'neighbor-count': 1,
                                               'network-type': 'BROADCAST_NETWORK',
                                               'passive': False,
                                               'priority': 1,
                                               'speed': '10000'}}}}}
