expected_output = {'routes': {'121.121.121.121/32': {'paths': [{'origin': '4.0.0.0',
                                              'path-id': '23',
                                              'valid-route': False,
                                              'invalid-reason': 'NEXT_HOP_UNREACHABLE',
                                              'next-hop': '91.1.1.1',
                                              'not-best-path-reason': 'Not Valid for Best-Path '
                                                                      'Selection',
                                              'path-types': [],
                                              'stale-route': False,
                                              'origin-attr': 'IGP',
                                              'local-pref': 100,
                                              'originator-id': '121.121.121.121',
                                              'cluster-list': ['4.0.0.0'],
                                              'weight': 0,
                                              'as-path-string': '123456'},
                                             {'origin': '5.0.0.0',
                                              'path-id': '527',
                                              'valid-route': True,
                                              'next-hop': '4.0.0.0',
                                              'path-types': ['BEST_PATH'],
                                              'stale-route': False,
                                              'origin-attr': 'IGP',
                                              'local-pref': 100,
                                              'originator-id': '121.121.121.121',
                                              'cluster-list': ['5.0.0.0', '3.0.0.0', '4.0.0.0'],
                                              'weight': 0,
                                              'as-path-string': '123456'},
                                             {'origin': '5.0.0.0',
                                              'path-id': '1',
                                              'valid-route': False,
                                              'invalid-reason': 'NEXT_HOP_UNREACHABLE',
                                              'next-hop': '90.1.1.1',
                                              'not-best-path-reason': 'Not Valid for Best-Path '
                                                                      'Selection',
                                              'stale-route': False,
                                              'origin-attr': 'IGP',
                                              'local-pref': 100,
                                              'originator-id': '121.121.121.121',
                                              'cluster-list': ['5.0.0.0'],
                                              'weight': 0,
                                              'as-path-string': '123456'}]}}}
